/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.nats.client.*;
import io.nats.client.api.*;
import io.nats.client.support.JsonParser;
import io.nats.client.support.JsonSerializable;
import io.nats.client.support.JsonValue;
import io.nats.client.support.JsonValueUtils;
import io.synadia.CommandLine;
import io.synadia.Workload;
import io.synadia.utils.Debug;

import java.io.IOException;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.locks.ReentrantLock;

import static io.nats.client.support.JsonUtils.printFormatted;
import static io.nats.jsmulti.shared.Stats.humanTime;
import static io.nats.jsmulti.shared.Utils.sleep;
import static io.synadia.utils.Constants.FULL_DATE_NO_TZ_FORMATTER;

@SuppressWarnings("SameParameterValue")
public abstract class AbstractCustomWorkload extends Workload {
    protected static final int NO_TIX = Integer.MIN_VALUE;
    protected static final String DEFAULT_SEGMENT = "._";
    protected static final String DOT = ".";

    protected String logStreamName;
    protected String logSubjectPrefix;
    protected String logStreamSubject;
    protected String exStreamName;
    protected String exSubjectPrefix;
    protected String exStreamSubject;
    protected long watchFrequency;
    protected int progressFrequency;
    protected String watchDateFormat;

    public void customWorkloadInit(String defaultLabel, boolean requiresArguments, CommandLine commandLine) {
        init(defaultLabel, commandLine);
        if (requiresArguments && commandLine.args.isEmpty()) {
            exit("Argument(s) Required");
        }

        logStreamName = JsonValueUtils.readString(params.jv, "log_stream_name", "log");
        logSubjectPrefix = JsonValueUtils.readString(params.jv, "log_subject_prefix", "log.");
        logStreamSubject = JsonValueUtils.readString(params.jv, "log_stream_subject", "log.>");
        exStreamName = JsonValueUtils.readString(params.jv, "ex_stream_name", "exception");
        exSubjectPrefix = JsonValueUtils.readString(params.jv, "ex_subject_prefix", "ex.");
        exStreamSubject = JsonValueUtils.readString(params.jv, "ex_stream_subject", "ex.>");
        watchFrequency = JsonValueUtils.readLong(params.jv, "watch_frequency", 5000);
        progressFrequency = JsonValueUtils.readInteger(params.jv, "progress_frequency", 100);
        watchDateFormat = JsonValueUtils.readString(params.jv, "watch_date_format", "HH:mm:ss.SSS");

        Debug.info(workLabel, "logStreamName", logStreamName);
        Debug.info(workLabel, "exStreamName", exStreamName);
        Debug.info(workLabel, "logSubjectPrefix", logSubjectPrefix);
        Debug.info(workLabel, "exSubjectPrefix", exSubjectPrefix);
        Debug.info(workLabel, "logStreamSubject", logStreamSubject);
        Debug.info(workLabel, "exStreamSubject", exStreamSubject);
        Debug.info(workLabel, "watchFrequency", watchFrequency);
        Debug.info(workLabel, "progressFrequency", progressFrequency);
        Debug.info(workLabel, "watchDateFormat", watchDateFormat);
    }

    protected void exit(String reason) {
        Debug.info(workLabel, reason);
        Debug.info(workLabel, "Commands", commands());
        System.exit(0);
    }

    protected abstract String[] commands();

    // ----------------------------------------------------------------------------------------------------
    // COMMANDS
    // ----------------------------------------------------------------------------------------------------
    @SuppressWarnings("SameParameterValue")
    protected void doSetup(JetStreamManagement jsm) throws IOException, JetStreamApiException {
        startJob("Setup");
        startJob("Creating Streams");
        List<String> streamNames = jsm.getStreamNames();
        for (String streamName : streamNames) {
            jsm.deleteStream(streamName);
        }
        StreamInfo si = jsm.addStream(StreamConfiguration.builder()
            .name(logStreamName)
            .subjects(logStreamSubject)
            .retentionPolicy(RetentionPolicy.Limits)
            .maxAge(Duration.ofMinutes(60))
            .build());
        printFormatted(si.getJv());
        si = jsm.addStream(StreamConfiguration.builder()
            .name(exStreamName)
            .subjects(exStreamSubject)
            .build());
        printFormatted(si.getJv());
    }

    protected void doClearLog(Connection nc) throws IOException, JetStreamApiException {
        startJob("Clear Log");
        nc.jetStreamManagement().purgeStream(logStreamName);
    }

    protected void doClearExceptions(Connection nc) throws IOException, JetStreamApiException {
        startJob("Clear Exception");
        nc.jetStreamManagement().purgeStream(exStreamName);
    }

    public static final String SUMMARY_TOP_LINE    = "├──────────────┬────────────┼────────────┬────────────┬────────────┬────────────┐";
    public static final String SUMMARY_LINE_HEADER = "│ Stream       │   Messages │   Subjects │  Consumers │ First Seq  │   Last Seq │";
    public static final String SUMMARY_SEP_LINE    = "├──────────────┼────────────┼────────────┼────────────┼────────────┼────────────┤";
    public static final String SUMMARY_FOOT_LINE   = "└──────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘";
    public static final String SUMMARY_LINE_FORMAT = "│ %-12s │ %10d │ %10d │ %10d │ %10d │ %10d │\n";

    public static final String DETAIL_TOP_LINE    = "├────────────────┬────────────────┼───────────────────────────────────────────────────────────────────────────────────────────┐";
    public static final String DETAIL_LINE_HEADER = "│ ? Job (Thread) │ Elapsed        │ Details                                                                                   │";
    public static final String DETAIL_SEP_LINE    = "├────────────────┼────────────────┼───────────────────────────────────────────────────────────────────────────────────────────┤";
    public static final String DETAIL_FOOT_LINE   = "└────────────────┴────────────────┴───────────────────────────────────────────────────────────────────────────────────────────┘";
    public static final String DETAIL_LINE_FORMAT = "│ %-14s │ %-14s │ %60s │\n";

    public static final String NON_DETAIL_TOP_LINE    = "├────────────────┬────────────────┬───────────────┤";
    public static final String NON_DETAIL_LINE_HEADER = "│ ? Job (Thread) │ Count          │ Elapsed       │";
    public static final String NON_DETAIL_SEP_LINE    = "├────────────────┼────────────────┼───────────────┤";
    public static final String NON_DETAIL_FOOT_LINE   = "└────────────────┴────────────────┴───────────────┘";
    public static final String NON_DETAIL_LINE_FORMAT = "│ %-14s │ %-14s │ %-13s │\n";

    @SuppressWarnings("InfiniteLoopStatement")
    protected void doWatch(Connection nc, String... customStreams) throws IOException {
        startJob("Watch");
        JetStreamManagement jsm = nc.jetStreamManagement();
        Map<String, Event> watchMap = new HashMap<>();
        while (true) {
            try {
                System.out.println();
                System.out.println();
                System.out.println("┌───────────────────────────┐");
                System.out.println("│ " + FULL_DATE_NO_TZ_FORMATTER.format(new Date()) + "   │");

                // STREAM SUMMARIES
                System.out.println(SUMMARY_TOP_LINE);
                System.out.println(SUMMARY_LINE_HEADER);
                System.out.println(SUMMARY_SEP_LINE);
                for (String stream : customStreams) {
                    summarize(jsm, stream);
                }
                StreamState exSs = summarize(jsm, exStreamName);
                StreamState logSs = summarize(jsm, logStreamName);
                System.out.println(SUMMARY_FOOT_LINE);

                watchStream(jsm, watchMap, true, exStreamName, exSs, v -> {
                    System.out.println("┌─────────────────────────────────┐");
                    System.out.println("│ Exceptions                      │");
                });

                watchStream(jsm, watchMap, false, logStreamName, logSs, v -> {
                    System.out.println("┌─────────────────────────────────────────────────┐");
                    System.out.println("│ Log                                             │");
                });
            }
            catch (Exception ignore) {}
            sleep(watchFrequency);
        }
    }

    private static StreamState summarize(JetStreamManagement jsm, String stream) throws IOException, JetStreamApiException {
        StreamInfo si = jsm.getStreamInfo(stream, StreamInfoOptions.allSubjects());
        StreamState ss = si.getStreamState();
        long fseq = si.getStreamState().getFirstSequence();
        long lseq = si.getStreamState().getLastSequence();
        System.out.printf(SUMMARY_LINE_FORMAT, stream, ss.getMsgCount(), ss.getSubjectCount(), ss.getConsumerCount(), fseq, lseq);
        return ss;
    }

    private void watchStream(JetStreamManagement jsm, Map<String, Event> watchMap, boolean detail, String streamName, StreamState ss, java.util.function.Consumer<Void> beforeFirst) {
        List<String> allSubjects = new ArrayList<>();
        for (Subject subject : ss.getSubjects()) {
            allSubjects.add(subject.getName());
        }
        Collections.sort(allSubjects);

        boolean first = true;
        for (String subject : allSubjects) {
            try {
                MessageInfo mi = jsm.getLastMessage(streamName, subject);
                if (mi != null) {
                    if (first) {
                        first = false;
                        beforeFirst.accept(null);
                        if (detail) {
                            System.out.println(DETAIL_TOP_LINE);
                            System.out.println(DETAIL_LINE_HEADER);
                            System.out.println(DETAIL_SEP_LINE);
                        }
                        else {
                            System.out.println(NON_DETAIL_TOP_LINE);
                            System.out.println(NON_DETAIL_LINE_HEADER);
                            System.out.println(NON_DETAIL_SEP_LINE);
                        }
                    }
                    Event prev = watchMap.get(subject);
                    Event event = new Event(mi.getData());
                    watchMap.put(subject, event);
                    String job = (prev == null || !prev.equals(event) ? "* " : "  ") + event.job;
                    if (event.tix != NO_TIX) {
                        job = job + " (" + event.tix + ")";
                    }

                    String ht = humanTime(event.elapsed);

                    if (detail) {
                        String deets = event.exceptionClass == null ? "" : event.exceptionClass + ": " + event.exceptionMessage.trim() + "                    ";
                        System.out.printf(DETAIL_LINE_FORMAT, job, ht, deets);
                    }
                    else {
                        String cnt = "";
                        if (event.count > 0) {
                            cnt = String.format("%,d", event.count);
                        }
                        System.out.printf(NON_DETAIL_LINE_FORMAT, job, cnt, ht);
                    }
                }
            }
            catch (IOException | JetStreamApiException ignore) {}
        }

        if (!first) {
            System.out.println(detail ? DETAIL_FOOT_LINE : NON_DETAIL_FOOT_LINE);
        }
    }

    // ----------------------------------------------------------------------------------------------------
    // WORKER
    // ----------------------------------------------------------------------------------------------------
    protected class WorkState {
        final String workId;
        private final ReentrantLock iLock;
        private final ReentrantLock uLock;
        private long groupCount;
        private long elapsed;
        final long startTime;

        public WorkState() {
            this.workId = generateWorkId();
            this.iLock = new ReentrantLock();
            this.uLock = new ReentrantLock();
            this.groupCount = 0;
            this.startTime = System.currentTimeMillis();
            this.elapsed = 0;
        }

        public long increment() {
            iLock.lock();
            try {
                return ++groupCount;
            }
            finally {
                iLock.unlock();
            }
        }

        public long elapse() {
            uLock.lock();
            try {
                elapsed = System.currentTimeMillis() - startTime;
            }
            finally {
                uLock.unlock();
            }
            return elapsed;
        }

    }

    protected interface Worker {
        Runnable getWork(Options options, int tix, WorkState workState);
    }

    protected void doWorker(String job, int threadCount, Worker worker) throws InterruptedException {
        startJob(job);
        List<Options> options = roundRobinOptions(threadCount);
        List<Thread> threads = new ArrayList<>(threadCount);
        WorkState ws = new WorkState();
        for (int tix = 0; tix < threadCount; tix++) {
            Thread t = new Thread(worker.getWork(options.get(tix), tix, ws));
            t.setName(job + " " + tix + " ");
            t.start();
            threads.add(t);
        }
        for (Thread t : threads) {
            t.join();
        }
    }

    // ----------------------------------------------------------------------------------------------------
    // GENERAL HELPERS
    // ----------------------------------------------------------------------------------------------------
    protected String generateWorkId() {
        return Long.toHexString(System.currentTimeMillis()).toLowerCase() + NUID.nextGlobalSequence();
    }

    // ----------------------------------------------------------------------------------------------------
    // EVENT
    // ----------------------------------------------------------------------------------------------------
    protected class Event implements JsonSerializable {
        public final String job;
        public final String workId;
        public final int tix;
        public final String qualifier;
        public final boolean defaultQualifier;
        public final long count;
        public final long elapsed;
        public final String exceptionClass;
        public final String exceptionMessage;

        public Event(byte[] jsonBytes) {
            JsonValue jv = JsonParser.parseUnchecked(jsonBytes);
            this.job = JsonValueUtils.readString(jv, "job");
            this.workId = JsonValueUtils.readString(jv, "work_id");
            this.tix = JsonValueUtils.readInteger(jv, "tix", NO_TIX);
            this.qualifier = JsonValueUtils.readString(jv, "qualifier");
            this.defaultQualifier = qualifier == null || qualifier.trim().isEmpty();
            this.count = JsonValueUtils.readLong(jv, "count", 0);
            this.elapsed = JsonValueUtils.readLong(jv, "elapsed", 0);

            this.exceptionClass = JsonValueUtils.readString(jv, "exception_class");
            this.exceptionMessage = JsonValueUtils.readString(jv, "exception_message");
        }

        public Event(String job, String workId, int tix, String qualifier, long count, long elapsed, Exception exception) {
            this.job = job;
            this.workId = workId;
            this.tix = tix;
            this.defaultQualifier = qualifier == null || qualifier.trim().isEmpty();
            if (defaultQualifier) {
                this.qualifier = null;
            }
            else {
                this.qualifier = qualifier.toLowerCase().replace(" ", "").trim();
            }
            this.count = count;
            this.elapsed = elapsed;
            if (exception == null) {
                exceptionClass = null;
                exceptionMessage = null;
            }
            else {
                exceptionClass = exception.getClass().getSimpleName();
                exceptionMessage = exception.getMessage();
            }
        }

        @Override
        public String toJson() {
            JsonValueUtils.MapBuilder mb = JsonValueUtils.mapBuilder();
            mb.put("job", job);
            if (tix != NO_TIX) {
                mb.put("tix", tix);
            }
            mb.put("work_id", workId);
            mb.put("qualifier", qualifier);
            mb.put("count", count);
            mb.put("elapsed", elapsed);
            mb.put("exception_class", exceptionClass);
            mb.put("exception_message", exceptionMessage);
            return mb.jv.toJson();
        }

        @Override
        public String toString() {
            return toJson();
        }

        public Object[] extras(String... messages) {
            List<Object> list = new ArrayList<>();
            if (count > 0) {
                list.add("Count: " + count);
            }
            if (exceptionClass != null) {
                list.add(exceptionClass + ": " + exceptionMessage);
            }
            list.add(humanTime(elapsed));
            if (messages != null) {
                for (String m : messages) {
                    if (m != null) {
                        list.add(m);
                    }
                }
            }
            return list.toArray();
        }

        public String subject() {
            return (exceptionClass == null  ? logSubjectPrefix : exSubjectPrefix)
                + segments(DEFAULT_SEGMENT);
        }

        public String ident() {
            return segments("");
        }

        private String segments(String missing) {
            return job
                // + (workId == null    ? missing : DOT + workId)
                + (defaultQualifier ? missing : DOT + qualifier)
                + (tix == NO_TIX    ? missing : DOT + tix);
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            Event event = (Event) o;
            return tix == event.tix
                && defaultQualifier == event.defaultQualifier && count == event.count && elapsed == event.elapsed && Objects.equals(job, event.job) && Objects.equals(workId, event.workId) && Objects.equals(qualifier, event.qualifier) && Objects.equals(exceptionClass, event.exceptionClass) && Objects.equals(exceptionMessage, event.exceptionMessage);
        }

        @Override
        public int hashCode() {
            int result = Objects.hashCode(job);
            result = 31 * result + Objects.hashCode(workId);
            result = 31 * result + tix;
            result = 31 * result + Objects.hashCode(qualifier);
            result = 31 * result + Boolean.hashCode(defaultQualifier);
            result = 31 * result + Long.hashCode(count);
            result = 31 * result + Long.hashCode(elapsed);
            result = 31 * result + Objects.hashCode(exceptionClass);
            result = 31 * result + Objects.hashCode(exceptionMessage);
            return result;
        }
    }

    // ----------------------------------------------------------------------------------------------------
    // EVENT HELPERS
    // ----------------------------------------------------------------------------------------------------

    protected void log(JetStream js, String job, String workId, int tix, long count, long elapsed) {
        Event event = new Event(job, workId, tix, null, count, elapsed, null);
        Debug.info(event.ident(), event.extras());
        publish(js, event);
    }

    protected void log(JetStream js, String job, String workId, long elapsed, Exception exception) {
        Event event = new Event(job, workId, NO_TIX, null, 0, elapsed, exception);
        Debug.info(event.ident(), event.extras());
        publish(js, event);
    }

    protected void print(String job, String workId, int tix, String qualifier, long count, long elapsed, String message) {
        Event event = new Event(job, workId, tix, qualifier, count, elapsed, null);
        Debug.info(event.ident(), event.extras(message));
    }

    protected void publish(JetStream js, Event event) {
        try {
            js.publish(event.subject(), event.serialize());
        }
        catch (IOException | JetStreamApiException ee) {
            Debug.info("Event Publish Error", event.ident(), event.subject(), ee.getClass().getSimpleName(), ee.getMessage(), event.extras());
        }
    }

    protected void showProgressMaybe(long count, String lineStart) {
        if (count % progressFrequency == 0) {
            System.out.println(" " + count);
            System.out.print(lineStart);
        }
        else {
            System.out.print(DOT);
        }
    }

    protected void endProgress(long count) {
        if (count % progressFrequency != 0) { // last check because I might have already printed this count
            System.out.println(" " + count);
        }
    }

    protected void startProgressJob(String job) {
        System.out.println(workLabel);
        System.out.print(job);
    }

    protected void startJob(String job) {
        System.out.println(workLabel + " - " + job);
    }
}
