/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.nats.client.*;
import io.nats.client.api.RetentionPolicy;
import io.nats.client.api.StreamConfiguration;
import io.nats.client.api.StreamInfo;
import io.nats.client.support.JsonParser;
import io.nats.client.support.JsonSerializable;
import io.nats.client.support.JsonValue;
import io.nats.client.support.JsonValueUtils;
import io.synadia.CommandLine;
import io.synadia.Workload;

import java.io.IOException;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

import static io.nats.client.support.JsonUtils.printFormatted;

public abstract class AbstractSimWorkload extends Workload {
    protected static final String DATA_STREAM_NAME = "sim-data";
    protected static final String RESULT_STREAM_NAME = "sim-log";
    protected static final String DATA_SUBJECT_PREFIX = "data.";
    protected static final String DATA_STREAM_SUBJECT = DATA_SUBJECT_PREFIX + ">";
    protected static final String RESULT_SUBJECT_PREFIX = "result.";
    protected static final String RESULT_STREAM_SUBJECT = RESULT_SUBJECT_PREFIX + ">";
    protected static final int WORKER_THREAD_COUNT = 3;

    protected final int progressFrequency;

    private Boolean _background;
    protected boolean isBackground() {
        if (_background == null) {
            _background = commandLine.args.contains("background");
        }
        return _background;
    }

    protected AbstractSimWorkload(int progressFrequency) {
        this.progressFrequency = progressFrequency;
    }

    public void init(String defaultLabel, boolean requiresArguments, CommandLine commandLine) {
        init(defaultLabel, commandLine);
        if (requiresArguments && commandLine.args.isEmpty()) {
            throw new RuntimeException("Argument(s) Required. " + commands());
        }
    }

    protected abstract String commands();

    @SuppressWarnings("SameParameterValue")
    protected void doSetup(Connection nc, long maxMessages) throws IOException, JetStreamApiException {
        printHeader("Setup");
        printHeader("Creating Streams");
        JetStreamManagement jsm = nc.jetStreamManagement();
        safeDeleteStream(jsm, DATA_STREAM_NAME);
        StreamInfo si = jsm.addStream(StreamConfiguration.builder()
            .name(DATA_STREAM_NAME)
            .subjects(DATA_STREAM_SUBJECT)
            .retentionPolicy(RetentionPolicy.WorkQueue)
            .maxMessages(maxMessages)
            .build());
        printFormatted(si.getJv());
        safeDeleteStream(jsm, RESULT_STREAM_NAME);
        si = jsm.addStream(StreamConfiguration.builder()
            .name(RESULT_STREAM_NAME)
            .subjects(RESULT_STREAM_SUBJECT)
            .retentionPolicy(RetentionPolicy.Limits)
            .maxAge(Duration.ofMinutes(5))
            .build());
        printFormatted(si.getJv());
    }

    protected interface Worker {
        Runnable getWork(String job, String runId, int tix, boolean background, Counts count, Options options);
    }

    protected void doWorker(String job, Worker worker) throws InterruptedException {
        boolean background = isBackground();
        printHeader(job, background);
        List<Options> options = roundRobinOptions(WORKER_THREAD_COUNT);
        List<Thread> threads = new ArrayList<>(WORKER_THREAD_COUNT);
        Counts groupCount = new Counts();
        String runId = generateRunId();
        for (int tix = 0; tix < WORKER_THREAD_COUNT; tix++) {
            Thread t = new Thread(worker.getWork(job, runId, tix, background, groupCount, options.get(tix)));
            t.start();
            threads.add(t);
        }
        for (Thread t : threads) {
            t.join();
        }
    }

    protected static class Counts {
        public final AtomicLong count = new AtomicLong();
        public final AtomicLong ioEx = new AtomicLong();
        public final AtomicLong jsapiEx = new AtomicLong();
    }

    protected String generateRunId() {
        return Long.toHexString(System.currentTimeMillis()).toLowerCase();
    }

    protected static class Result implements JsonSerializable {
        public final String job;
        public final String runId;
        public final int tix;
        public final String operation;
        public final long count;
        public final long groupCount;
        public final long time;
        public final String details;

        public Result(byte[] jsonBytes) {
            JsonValue jv = JsonParser.parseUnchecked(jsonBytes);
            this.job = JsonValueUtils.readString(jv, "job");
            this.runId = JsonValueUtils.readString(jv, "run_id");
            this.tix = JsonValueUtils.readInteger(jv, "tix", -1);
            this.operation = JsonValueUtils.readString(jv, "operation");
            this.count = JsonValueUtils.readLong(jv, "count", 0);
            this.groupCount = JsonValueUtils.readLong(jv, "group_count", -1);
            this.time = JsonValueUtils.readLong(jv, "time", 0);
            this.details = JsonValueUtils.readString(jv, "details");
        }

        public Result(String job, String runId, int tix, String operation, long count, long groupCount, Object details) {
            this.job = job;
            this.runId = runId;
            this.tix = tix;
            this.operation = operation;
            this.count = count;
            this.groupCount = groupCount;
            this.time = System.currentTimeMillis();
            this.details = details == null ? null : details.toString().trim();
        }

        @Override
        public String toJson() {
            JsonValueUtils.MapBuilder mb = JsonValueUtils.mapBuilder();
            mb.put("job", job);
            mb.put("tix", tix);
            mb.put("run_id", runId);
            mb.put("operation", operation);
            mb.put("count", count);
            mb.put("group_count", groupCount);
            mb.put("time", time);
            mb.put("details", details);
            return mb.jv.toJson();
        }

        @Override
        public String toString() {
            String xs = details == null ? "" : details;
            return "[" + time + "]" + printLabel()
                + (count < 0 ? "" : " | Count: " + count)
                + (xs.isEmpty() ? "" : " | " + xs);
        }

        public String printLabel() {
            return "[" + job + "-" + runId + "-" + tix + "][" + operation + "]";
        }

        public String subject() {
            return RESULT_SUBJECT_PREFIX + job + "." + runId + "." + tix;
        }
    }

    protected void autoProgress(boolean background, JetStream js, String job, String runId, int tix, String operation, long count, long groupCount, Object details) {
        showProgressMaybe(background, groupCount > 0 ? groupCount : count);
        publishResult(js, job, runId, tix, operation, count, groupCount, details);
    }

    protected void autoResult(boolean background, JetStream js, String job, String runId, int tix, String operation, long count, long groupCount, Object details) {
        Result result = new Result(job, runId, tix, operation, count, groupCount, details);
        if (!background) {
            System.out.println(result);
        }
        publishResult(js, result);
    }

    protected void autoException(boolean background, JetStream js, String job, String runId, int tix, long count, long groupCount, Exception ex) {
        autoResult(background, js, job, runId, tix, "Exception", count, groupCount, ex);
    }

    protected void publishResult(JetStream js, String job, String runId, int tix, String operation, long count, long groupCount, Object details) {
        publishResult(js, new Result(job, runId, tix, operation, count, groupCount, details));
    }

    protected void publishResult(JetStream js, Result result) {
        try {
            js.publish(result.subject(), result.serialize());
        }
        catch (IOException | JetStreamApiException ee) {
            System.err.println(result.printLabel() + " Result Publish Error | " + ee);
        }
    }

    protected void showProgressMaybe(boolean background, long count) {
        if (!background) {
            System.out.print(".");
            if (count % progressFrequency == 0) {
                System.out.println(count);
            }
        }
    }

    protected void print(boolean background, String message) {
        if (!background) {
            System.out.println(System.lineSeparator() + message);
        }
    }

    protected void endProgress(boolean background, long count) {
        if (!background && count % progressFrequency != 0) { // last check because I might have already printed this count
            System.out.println(count);
        }
    }

    protected void printHeader(String job) {
        System.out.println(workLabel + " - " + job);
    }

    protected void printHeader(String job, boolean background) {
        System.out.println(workLabel + " - " + job + " (background=" + background + ")");
    }
}
