/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.nats.client.*;
import io.nats.client.api.*;
import io.nats.client.support.JsonParser;
import io.nats.client.support.JsonSerializable;
import io.nats.client.support.JsonValue;
import io.nats.client.support.JsonValueUtils;
import io.synadia.CommandLine;
import io.synadia.Workload;
import io.synadia.utils.Debug;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.locks.ReentrantLock;

import static io.nats.client.support.JsonUtils.printFormatted;
import static io.nats.jsmulti.shared.Stats.humanTime;
import static io.nats.jsmulti.shared.Utils.sleep;

@SuppressWarnings("SameParameterValue")
public abstract class AbstractSimWorkload extends Workload {
    protected static final String DATA_STREAM_NAME = "sim-data";
    protected static final String INFO_STREAM_NAME = "sim-info";
    protected static final String EX_STREAM_NAME = "sim-exception";
    protected static final String DATA_SUBJECT_PREFIX = "data.";
    protected static final String INFO_SUBJECT_PREFIX = "info.";
    protected static final String EX_SUBJECT_PREFIX = "ex.";
    protected static final String DATA_STREAM_SUBJECT = DATA_SUBJECT_PREFIX + ">";
    protected static final String INFO_STREAM_SUBJECT = INFO_SUBJECT_PREFIX + ">";
    protected static final String EX_STREAM_SUBJECT = EX_SUBJECT_PREFIX + ">";
    protected static final int DEFAULT_WORKER_THREAD_COUNT = 3;
    protected static final int NO_TIX = Integer.MIN_VALUE;
    protected static final String DEFAULT_SEGMENT = "._";
    protected static final String DOT = ".";
    protected static final long WATCH_FREQUENCY = 5000;

    protected final int progressFrequency;

    protected AbstractSimWorkload(int progressFrequency) {
        this.progressFrequency = progressFrequency;
    }

    public void aswInit(String defaultLabel, boolean requiresArguments, CommandLine commandLine) {
        init(defaultLabel, commandLine);
        if (requiresArguments && commandLine.args.isEmpty()) {
            exit("Argument(s) Required");
        }
    }

    protected void exit(String reason) {
        Debug.info(workLabel, reason);
        Debug.info(workLabel, "Commands: " + commands());
        System.exit(0);
    }

    protected abstract String commands();

    // ----------------------------------------------------------------------------------------------------
    // COMMANDS
    // ----------------------------------------------------------------------------------------------------
    @SuppressWarnings("SameParameterValue")
    protected void doSetup(Connection nc, long maxMessages) throws IOException, JetStreamApiException {
        startJob("Setup");
        startJob("Creating Streams");
        JetStreamManagement jsm = nc.jetStreamManagement();
        safeDeleteStream(jsm, DATA_STREAM_NAME);
        StreamInfo si = jsm.addStream(StreamConfiguration.builder()
            .name(DATA_STREAM_NAME)
            .subjects(DATA_STREAM_SUBJECT)
            .retentionPolicy(RetentionPolicy.WorkQueue)
            .maxMessages(maxMessages)
            .build());
        printFormatted(si.getJv());
        safeDeleteStream(jsm, INFO_STREAM_NAME);
        si = jsm.addStream(StreamConfiguration.builder()
            .name(INFO_STREAM_NAME)
            .subjects(INFO_STREAM_SUBJECT)
            .retentionPolicy(RetentionPolicy.Limits)
            .maxAge(Duration.ofMinutes(60))
            .build());
        printFormatted(si.getJv());
        safeDeleteStream(jsm, EX_STREAM_NAME);
        si = jsm.addStream(StreamConfiguration.builder()
            .name(EX_STREAM_NAME)
            .subjects(EX_STREAM_SUBJECT)
            .build());
        printFormatted(si.getJv());
    }

    protected void doClearData(Connection nc) throws IOException, JetStreamApiException {
        startJob("Clear Data");
        nc.jetStreamManagement().purgeStream(DATA_STREAM_NAME);
    }

    protected void doClearInfo(Connection nc) throws IOException, JetStreamApiException {
        startJob("Clear Info");
        nc.jetStreamManagement().purgeStream(INFO_STREAM_NAME);
    }

    protected void doClearExceptions(Connection nc) throws IOException, JetStreamApiException {
        startJob("Clear Exception");
        nc.jetStreamManagement().purgeStream(INFO_STREAM_NAME);
    }

    @SuppressWarnings("InfiniteLoopStatement")
    protected void doWatch(Connection nc) throws IOException {
        startJob("Watch");
        JetStreamManagement jsm = nc.jetStreamManagement();
        Map<String, Event> watchMap = new HashMap<>();
        while (true) {
            try {
                System.out.println();
                System.out.println();
                System.out.println(WATCH_BREAK);
                StreamInfo dataSi = jsm.getStreamInfo(DATA_STREAM_NAME);
                StreamState dataSs = dataSi.getStreamState();
                System.out.println("STREAM | " + pad(DATA_STREAM_NAME, 10) + " | Subjects: " + pad(dataSs.getSubjectCount(), 10) + " | Messages: " + pad(dataSs.getMsgCount(), 12));

                StreamInfo exSi = jsm.getStreamInfo(EX_STREAM_NAME, StreamInfoOptions.allSubjects());
                StreamState exSs = exSi.getStreamState();
                System.out.println("STREAM | " + pad(EX_STREAM_NAME, 10) + " | Subjects: " + pad(exSs.getSubjectCount(), 10) + " | Messages: " + pad(exSs.getMsgCount(), 12));

                StreamInfo infoSi = jsm.getStreamInfo(INFO_STREAM_NAME, StreamInfoOptions.allSubjects());
                StreamState infoSs = infoSi.getStreamState();
                System.out.println("STREAM | " + pad(INFO_STREAM_NAME, 10) + " | Subjects: " + pad(infoSs.getSubjectCount(), 10) + " | Messages: " + pad(infoSs.getMsgCount(), 12));

                System.out.println(WATCH_BREAK);
                boolean hadAnyMessages = watchStream(jsm, watchMap, EX_STREAM_NAME, infoSs, "EX     | ");

                if (hadAnyMessages) { System.out.println(WATCH_BREAK); }
                watchStream(jsm, watchMap, INFO_STREAM_NAME, infoSs, "INFO   | ");

                System.out.println(WATCH_BREAK);
                sleep(WATCH_FREQUENCY);
            }
            catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
    }

    private static final SimpleDateFormat WATCH_DATE_FORMAT = new SimpleDateFormat("HH:mm:ss.SSS");

    private static boolean watchStream(JetStreamManagement jsm, Map<String, Event> watchMap, String streamName, StreamState ss, String lineStart) {
        List<String> allSubjects = new ArrayList<>();
        for (Subject subject : ss.getSubjects()) {
            allSubjects.add(subject.getName());
        }
        Collections.sort(allSubjects);

        boolean hadAnyMessages = false;
        boolean first = true;
        for (String subject : allSubjects) {
            try {
                MessageInfo mi = jsm.getLastMessage(streamName, subject);
                if (mi != null) {
                    hadAnyMessages = true;
                    if (first) {
                        first = false;
                        System.out.println("       | ? Job (Thread)  | Count       | Elapsed        | Details");
                        System.out.println("       | --------------- | ----------- | -------------- | ----------------------------------------------------");
                    }
                    Event prev = watchMap.get(subject);
                    Event event = new Event(mi.getData());
                    watchMap.put(subject, event);
                    StringBuilder sb = new StringBuilder(lineStart);
                    sb.append(prev == null || !prev.equals(event) ? "* " : "  ");
                    String temp = event.job;
                    if (event.tix != NO_TIX) {
                        temp = temp + " (" + event.tix + ")";
                    }
                    sb.append(pad(temp, 13)).append(" | ");
                    temp = "";
                    if (event.count > 0) {
                        temp = String.format("%,d", event.count);
                    }
                    sb.append(pad(temp, 11))
                        .append(" | ")
                        .append(pad(humanTime(event.elapsed), 14));

                    if (event.exceptionClass == null) {
                        sb.append(" |");
                    }
                    else {
                        sb.append(" | ").append(event.exceptionClass).append(": ").append(event.exceptionMessage);
                    }
                    System.out.println(sb);
                }
            }
            catch (IOException | JetStreamApiException ignore) {}
        }
        return hadAnyMessages;
    }

    // ----------------------------------------------------------------------------------------------------
    // WORKER
    // ----------------------------------------------------------------------------------------------------
    protected class WorkState {
        final String workId;
        private final ReentrantLock iLock;
        private final ReentrantLock uLock;
        private long count;
        private long elapsed;
        final long startTime;

        public WorkState() {
            this.workId = generateWorkId();
            this.iLock = new ReentrantLock();
            this.uLock = new ReentrantLock();
            this.count = 0;
            this.startTime = System.currentTimeMillis();
            this.elapsed = 0;
        }

        public long increment() {
            iLock.lock();
            try {
                return ++count;
            }
            finally {
                iLock.unlock();
            }
        }

        public long elapse() {
            uLock.lock();
            try {
                elapsed = System.currentTimeMillis() - startTime;
            }
            finally {
                uLock.unlock();
            }
            return elapsed;
        }

    }

    protected interface Worker {
        Runnable getWork(Options options, int tix, WorkState workState);
    }

    protected void doWorker(String job, Worker worker) throws InterruptedException {
        doWorker(job, DEFAULT_WORKER_THREAD_COUNT, worker);
    }

    protected void doWorker(String job, int threadCount, Worker worker) throws InterruptedException {
        startJob(job);
        List<Options> options = roundRobinOptions(threadCount);
        List<Thread> threads = new ArrayList<>(threadCount);
        WorkState ws = new WorkState();
        for (int tix = 0; tix < threadCount; tix++) {
            Thread t = new Thread(worker.getWork(options.get(tix), tix, ws));
            t.start();
            threads.add(t);
        }
        for (Thread t : threads) {
            t.join();
        }
    }

    // ----------------------------------------------------------------------------------------------------
    // GENERAL HELPERS
    // ----------------------------------------------------------------------------------------------------
    protected String generateWorkId() {
        return Long.toHexString(System.currentTimeMillis()).toLowerCase() + NUID.nextGlobalSequence();
    }

    // ----------------------------------------------------------------------------------------------------
    // EVENT
    // ----------------------------------------------------------------------------------------------------
    protected static class Event implements JsonSerializable {
        public final String job;
        public final String workId;
        public final int tix;
        public final String qualifier;
        public final boolean defaultQualifier;
        public final long count;
        public final long elapsed;
        public final String exceptionClass;
        public final String exceptionMessage;

        public Event(byte[] jsonBytes) {
            JsonValue jv = JsonParser.parseUnchecked(jsonBytes);
            this.job = JsonValueUtils.readString(jv, "job");
            this.workId = JsonValueUtils.readString(jv, "work_id");
            this.tix = JsonValueUtils.readInteger(jv, "tix", NO_TIX);
            this.qualifier = JsonValueUtils.readString(jv, "qualifier");
            this.defaultQualifier = qualifier == null || qualifier.trim().isEmpty();
            this.count = JsonValueUtils.readLong(jv, "count", 0);
            this.elapsed = JsonValueUtils.readLong(jv, "elapsed", 0);

            this.exceptionClass = JsonValueUtils.readString(jv, "exception_class");
            this.exceptionMessage = JsonValueUtils.readString(jv, "exception_message");
        }

        public Event(String job, String workId, int tix, String qualifier, long count, long elapsed, Exception exception) {
            this.job = job;
            this.workId = workId;
            this.tix = tix;
            this.defaultQualifier = qualifier == null || qualifier.trim().isEmpty();
            if (defaultQualifier) {
                this.qualifier = null;
            }
            else {
                this.qualifier = qualifier.toLowerCase().replace(" ", "").trim();
            }
            this.count = count;
            this.elapsed = elapsed;
            if (exception == null) {
                exceptionClass = null;
                exceptionMessage = null;
            }
            else {
                exceptionClass = exception.getClass().getSimpleName();
                exceptionMessage = exception.getMessage();
            }
        }

        @Override
        public String toJson() {
            JsonValueUtils.MapBuilder mb = JsonValueUtils.mapBuilder();
            mb.put("job", job);
            if (tix != NO_TIX) {
                mb.put("tix", tix);
            }
            mb.put("work_id", workId);
            mb.put("qualifier", qualifier);
            mb.put("count", count);
            mb.put("elapsed", elapsed);
            mb.put("exception_class", exceptionClass);
            mb.put("exception_message", exceptionMessage);
            return mb.jv.toJson();
        }

        @Override
        public String toString() {
            return toJson();
        }

        public Object[] extras(String... messages) {
            List<Object> list = new ArrayList<>();
            if (count > 0) {
                list.add("Count: " + count);
            }
            if (exceptionClass != null) {
                list.add(exceptionClass + ": " + exceptionMessage);
            }
            list.add(humanTime(elapsed));
            if (messages != null) {
                for (String m : messages) {
                    if (m != null) {
                        list.add(m);
                    }
                }
            }
            return list.toArray();
        }

        public String subject() {
            return (exceptionClass == null  ? INFO_SUBJECT_PREFIX : EX_SUBJECT_PREFIX)
                + segments(DEFAULT_SEGMENT);
        }

        public String ident() {
            return segments("");
        }

        private String segments(String missing) {
            return job
                // + (workId == null    ? missing : DOT + workId)
                + (defaultQualifier ? missing : DOT + qualifier)
                + (tix == NO_TIX    ? missing : DOT + tix);
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            Event event = (Event) o;
            return tix == event.tix
                && defaultQualifier == event.defaultQualifier && count == event.count && elapsed == event.elapsed && Objects.equals(job, event.job) && Objects.equals(workId, event.workId) && Objects.equals(qualifier, event.qualifier) && Objects.equals(exceptionClass, event.exceptionClass) && Objects.equals(exceptionMessage, event.exceptionMessage);
        }

        @Override
        public int hashCode() {
            int result = Objects.hashCode(job);
            result = 31 * result + Objects.hashCode(workId);
            result = 31 * result + tix;
            result = 31 * result + Objects.hashCode(qualifier);
            result = 31 * result + Boolean.hashCode(defaultQualifier);
            result = 31 * result + Long.hashCode(count);
            result = 31 * result + Long.hashCode(elapsed);
            result = 31 * result + Objects.hashCode(exceptionClass);
            result = 31 * result + Objects.hashCode(exceptionMessage);
            return result;
        }
    }

    // ----------------------------------------------------------------------------------------------------
    // EVENT HELPERS
    // ----------------------------------------------------------------------------------------------------
    protected static final String WATCH_BREAK = "--------------------------------------------------------------------------------------------------------------";

    protected void logInfo(JetStream js, String job, String workId, int tix, long count, long elapsed) {
        Event event = new Event(job, workId, tix, null, count, elapsed, null);
        Debug.info(event.ident(), event.extras());
        publish(js, event);
    }

    protected void logException(JetStream js, String job, String workId, long elapsed, Exception exception) {
        Event event = new Event(job, workId, NO_TIX, null, 0, elapsed, exception);
        Debug.info(event.ident(), event.extras());
        publish(js, event);
    }

    protected void print(String job, String workId, int tix, String qualifier, long count, long elapsed, String message) {
        Event event = new Event(job, workId, tix, qualifier, count, elapsed, null);
        Debug.info(event.ident(), event.extras(message));
    }

    protected void publish(JetStream js, Event event) {
        try {
            js.publish(event.subject(), event.serialize());
        }
        catch (IOException | JetStreamApiException ee) {
            Debug.info("Event Publish Error", event.ident(), event.subject(), ee.getClass().getSimpleName(), ee.getMessage(), event.extras());
        }
    }

    protected void showProgressMaybe(long count, String lineStart) {
        if (count % progressFrequency == 0) {
            System.out.println(" " + count);
            System.out.print(lineStart);
        }
        else {
            System.out.print(DOT);
        }
    }

    protected void endProgress(long count) {
        if (count % progressFrequency != 0) { // last check because I might have already printed this count
            System.out.println(" " + count);
        }
    }

    protected void startProgressJob(String job) {
        System.out.println(workLabel);
        System.out.print(job);
    }

    protected void startJob(String job) {
        System.out.println(workLabel + " - " + job);
    }
}
