/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.nats.client.*;
import io.nats.client.api.*;
import io.nats.client.support.*;
import io.synadia.Workload;
import io.synadia.utils.Debug;

import java.io.IOException;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.locks.ReentrantLock;

import static io.nats.client.support.JsonUtils.printFormatted;
import static io.nats.client.support.NatsObjectStoreUtil.OBJ_STREAM_PREFIX;
import static io.nats.jsmulti.shared.Stats.humanBytes;
import static io.nats.jsmulti.shared.Stats.humanTime;
import static io.nats.jsmulti.shared.Utils.sleep;

@SuppressWarnings("SameParameterValue")
public abstract class AbstractCustomWorkload extends Workload {
    protected static final int NO_TIX = Integer.MIN_VALUE;
    protected static final String DEFAULT_SEGMENT = "._";
    protected static final String DOT = ".";

    protected String logStreamName;
    protected String logSubjectPrefix;
    protected String logStreamSubject;
    protected String exStreamName;
    protected String exSubjectPrefix;
    protected String exStreamSubject;
    protected long watchFrequency;
    protected int progressFrequency;
    protected String watchDateFormat;

    protected List<String> customStreams;
    protected String commandHelp;

    // ----------------------------------------------------------------------------------------------------
    // INITIALIZATION
    // ----------------------------------------------------------------------------------------------------
    protected void initCustom(String[] commands, String[] customStreams) {
        // build help first...
        buildCommandHelp(commands, customStreams);

        // all workloads in this hierarchy expect at least 1 arg...
        if (commandLine.args.isEmpty()) {
            exit("Argument(s) Required");
        }

        this.customStreams = new ArrayList<>(Arrays.asList(customStreams));

        // common
        logStreamName = JsonValueUtils.readString(params.jv, "log_stream_name", "log");
        logSubjectPrefix = JsonValueUtils.readString(params.jv, "log_subject_prefix", "log.");
        logStreamSubject = JsonValueUtils.readString(params.jv, "log_stream_subject", "log.>");
        exStreamName = JsonValueUtils.readString(params.jv, "ex_stream_name", "ex");
        exSubjectPrefix = JsonValueUtils.readString(params.jv, "ex_subject_prefix", "ex.");
        exStreamSubject = JsonValueUtils.readString(params.jv, "ex_stream_subject", "ex.>");
        watchFrequency = JsonValueUtils.readLong(params.jv, "watch_frequency", 5000);
        progressFrequency = JsonValueUtils.readInteger(params.jv, "progress_frequency", 100);
        watchDateFormat = JsonValueUtils.readString(params.jv, "watch_date_format", "HH:mm:ss.SSS");

        Debug.info(workLabel, "logStreamName", logStreamName);
        Debug.info(workLabel, "exStreamName", exStreamName);
        Debug.info(workLabel, "logSubjectPrefix", logSubjectPrefix);
        Debug.info(workLabel, "exSubjectPrefix", exSubjectPrefix);
        Debug.info(workLabel, "logStreamSubject", logStreamSubject);
        Debug.info(workLabel, "exStreamSubject", exStreamSubject);
        Debug.info(workLabel, "watchFrequency", watchFrequency);
        Debug.info(workLabel, "progressFrequency", progressFrequency);
        Debug.info(workLabel, "watchDateFormat", watchDateFormat);
    }

    private void buildCommandHelp(String[] commands, String[] customStreams) {
        StringBuilder ssb = new StringBuilder();
        boolean first = true;
        for (String cs : customStreams) {
            if(first) {
                first = false;
            }
            else {
                ssb.append('|');
            }
            ssb.append(cs);
        }
        ssb.append("|log|ex");

        StringBuilder sb = new StringBuilder();
        sb.append("\n- setup");
        for (String command : commands) {
            sb.append("\n- ");
            sb.append(command);
        }
        sb.append("\n- watch");
        sb.append("\n- stream ").append(ssb);
        sb.append("\n- purge ").append(ssb).append(" (<filter>)");
        commandHelp = sb.toString();
    }

    protected void exit(String reason) {
        Debug.info(workLabel, reason);
        Debug.info(workLabel, "Commands", commandHelp);
        System.exit(0);
    }

    // ----------------------------------------------------------------------------------------------------
    // WORKLOAD START POINT
    // ----------------------------------------------------------------------------------------------------
    @Override
    public void runWorkload() throws Exception {
        String arg = commandLine.args.getFirst();
        switch (arg) {
            case "setup"  -> doSetup();
            case "watch"  -> doWatch();
            case "stream" -> doStream();
            case "purge"  -> doPurge();
            default -> {
                if (!subRunWorkload(arg)) {
                    exit("Unknown custom workload command: '" + arg + "'");
                }
            }
        }
    }

    protected boolean subRunWorkload(String arg) throws Exception {
        return false;
    }

    // ----------------------------------------------------------------------------------------------------
    // COMMANDS
    // ----------------------------------------------------------------------------------------------------
    protected interface AdminCommand {
        void run(Connection nc, JetStreamManagement jsm) throws IOException, JetStreamApiException, InterruptedException;
    }

    protected void runAdminCommand(AdminCommand cmd) throws IOException, JetStreamApiException, InterruptedException {
        try (Connection nc = Nats.connect(getAdminOptions())) {
            cmd.run(nc, nc.jetStreamManagement());
        }
    }

    // ----------------------------------------------------------------------------------------------------
    // COMMAND: SETUP
    // ----------------------------------------------------------------------------------------------------
    @SuppressWarnings("SameParameterValue")
    protected void doSetup() throws IOException, JetStreamApiException, InterruptedException {
        runAdminCommand((nc, jsm) -> {
            startJob("Setup");
            startJob("Creating Streams");
            List<String> streamNames = jsm.getStreamNames();
            for (String streamName : streamNames) {
                jsm.deleteStream(streamName);
            }
            addStream(jsm, StreamConfiguration.builder()
                .name(logStreamName)
                .subjects(logStreamSubject)
                .retentionPolicy(RetentionPolicy.Limits)
                .maxAge(Duration.ofMinutes(60))
                .build());
            addStream(jsm, StreamConfiguration.builder()
                .name(exStreamName)
                .subjects(exStreamSubject)
                .build());
            subDoSetup(nc, jsm);
        });
    }

    protected void subDoSetup(Connection nc, JetStreamManagement jsm) throws IOException, JetStreamApiException, InterruptedException {}

    protected static void addStream(JetStreamManagement jsm, StreamConfiguration sc) throws IOException, JetStreamApiException {
        StreamInfo si = jsm.addStream(sc);
        printFormatted(si.getJv());
    }

    // ----------------------------------------------------------------------------------------------------
    // COMMAND: CLEAR
    // ----------------------------------------------------------------------------------------------------
    protected void doPurge() throws IOException, JetStreamApiException, InterruptedException {
        String option = getStringArgFromPosition(2);
        if (option == null || option.isEmpty()) {
            exit("Purge stream not provided");
            return;
        }
        if (option.equals("log")) {
            doPurge(logStreamName);
        }
        else if (option.equals("ex")) {
            doPurge(exStreamName);
        }
        else if (customStreams.contains(option)) {
            doPurge(option);
        }
        else {
            exit("Unknown purge option: '" + option + "'");
        }
    }

    // ----------------------------------------------------------------------------------------------------
    // COMMAND: PURGE
    // ----------------------------------------------------------------------------------------------------
    protected void doPurge(String streamName) throws IOException, JetStreamApiException, InterruptedException {
        runAdminCommand((nc, jsm) -> {
            String filter = getStringArgFromPosition(2);
            if (filter == null || filter.isEmpty()) {
                startJob("Purge " + streamName);
                nc.jetStreamManagement().purgeStream(streamName);
            }
            else {
                startJob("Purge " + streamName + " (" + filter + ")");
                jsm.purgeStream(logStreamName, PurgeOptions.builder().subject(filter).build());
            }
        });
    }

    // ----------------------------------------------------------------------------------------------------
    // COMMAND: WATCH
    // ----------------------------------------------------------------------------------------------------
    public static final String SUMMARY_START   = "┌────────────────────────────────────────────────────────────────────────────────────────────┐";
    public static final String SUMMARY_DESC    = "│ Stream Information                                                     " + Debug.rfcTime() + " │";
    public static final String SUMMARY_TOP_SEP = "├──────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┤";
    public static final String SUMMARY_HEADER  = "│ Stream       │   Messages │   Subjects │  Consumers │  First Seq │   Last Seq │      Bytes │";
    public static final String SUMMARY_SEP     = "├──────────────┼────────────┼────────────┼────────────┼────────────┼────────────┼────────────┤";
    public static final String SUMMARY_FOOT    = "└──────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘";
    public static final String SUMMARY_DATA    = "│ %-12s │ %,10d │ %,10d │ %,10d │ %,10d │ %,10d │ %10s │\n";

    public static final String EX_START   = "┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐";
    public static final String EX_DESC    = "│ Exceptions                                                                                                                 │";
    public static final String EX_TOP_SEP = "├────────────────┬─────────────────────┬───────┬─────────────────────────────────────────────────────────────────────────────┤";
    public static final String EX_HEADER  = "│ ? Job (Thread) │ Last Occurrence     │ Count │ Exception                                                                   │";
    public static final String EX_SEP     = "├────────────────┼─────────────────────┼───────┼─────────────────────────────────────────────────────────────────────────────┤";
    public static final String EX_FOOT    = "└────────────────┴─────────────────────┴───────┴─────────────────────────────────────────────────────────────────────────────┘";
    public static final String EX_DATA    = "│ %-14s │ %-17s │ %,5d │ %-75s │\n";
    public static final int EX_WIDTH = 75;

    public static final String LOG_START      = "┌────────────────────────────────────────────────────┐";
    public static final String LOG_DESC       = "│ Log                                                │";
    public static final String LOG_TOP_SEP    = "├───────────────────┬────────────────┬───────────────┤";
    public static final String LOG_HEADER     = "│ ? Job (Thread)    │ Count          │ Elapsed       │";
    public static final String LOG_SEP_LINE   = "├───────────────────┼────────────────┼───────────────┤";
    public static final String LOG_FOOT_LINE  = "└───────────────────┴────────────────┴───────────────┘";
    public static final String LOG_DATA       = "│ %-17s │ %-14s │ %-13s │\n";

    public static final String OBJ_START      = "┌────────────────────────────────────────┐";
    public static final String OBJ_DESC       = "│ Object Stores                          │";
    public static final String OBJ_TOP_LINE   = "├──────────────┬────────────┬────────────┤";
    public static final String OBJ_HEADER     = "│ Bucket       │    Objects │     Chunks │";
    public static final String OBJ_SEP_LINE   = "├──────────────┼────────────┼────────────┤";
    public static final String OBJ_FOOT_LINE  = "└──────────────┴────────────┴────────────┘";
    public static final String OBJ_LINE_FMT_1 = "│ %-12s ...";
    public static final String OBJ_LINE_FMT_2 = "\b\b\b│ %,10d │ %,10d │\n";

    @SuppressWarnings("InfiniteLoopStatement")
    protected void doWatch() throws IOException, JetStreamApiException, InterruptedException {
        runAdminCommand((nc, jsm) -> {
            startJob("Watch");
            Map<String, Event> watchMap = new HashMap<>();
            List<String> objectStreams = new ArrayList<>();
            for (String stream : customStreams) {
                if (isOsStream(stream)) {
                    objectStreams.add(stream);
                }
            }
            boolean hasObjectStreams = !objectStreams.isEmpty();

            while (true) {
                try {
                    System.out.println("\n\n\n\n");
                    System.out.println(SUMMARY_START);
                    System.out.println(SUMMARY_DESC);

                    // STREAM SUMMARIES
                    System.out.println(SUMMARY_TOP_SEP);
                    System.out.println(SUMMARY_HEADER);
                    System.out.println(SUMMARY_SEP);
                    for (String stream : customStreams) {
                        summarize(jsm, stream);
                    }
                    System.out.println(SUMMARY_SEP);
                    StreamState exSs = summarize(jsm, exStreamName);
                    StreamState logSs = summarize(jsm, logStreamName);
                    System.out.println(SUMMARY_FOOT);

                    watchStream(jsm, watchMap, true, exStreamName, exSs, v -> {
                        System.out.println(EX_START);
                        System.out.println(EX_DESC);
                    });

                    watchStream(jsm, watchMap, false, logStreamName, logSs, v -> {
                        System.out.println(LOG_START);
                        System.out.println(LOG_DESC);
                    });

                    if (hasObjectStreams) {
                        System.out.println(OBJ_START);
                        System.out.println(OBJ_DESC);

                        // OBJECT SUMMARIES
                        System.out.println(OBJ_TOP_LINE);
                        System.out.println(OBJ_HEADER);
                        System.out.println(OBJ_SEP_LINE);
                        for (String stream : objectStreams) {
                            summarizeObjectStream(nc, stream);
                        }
                        System.out.println(OBJ_FOOT_LINE);
                    }
                }
                catch (Exception ignore) {}
                sleep(watchFrequency);
            }
        });
    }

    protected static StreamState summarize(JetStreamManagement jsm, String stream) throws IOException, JetStreamApiException {
        StreamInfo si = jsm.getStreamInfo(stream, StreamInfoOptions.allSubjects());
        StreamState ss = si.getStreamState();
        long fseq = si.getStreamState().getFirstSequence();
        long lseq = si.getStreamState().getLastSequence();
        System.out.printf(SUMMARY_DATA, stream, ss.getMsgCount(), ss.getSubjectCount(), ss.getConsumerCount(), fseq, lseq, humanBytes(ss.getByteCount()));
        return ss;
    }

    protected static void summarizeObjectStream(Connection nc, String bucketStreamName) throws IOException, JetStreamApiException {
        String bucketName = NatsObjectStoreUtil.extractBucketName(bucketStreamName);
        StreamContext ctx = nc.getStreamContext(bucketStreamName);
        String filter = NatsObjectStoreUtil.toMetaStreamSubject(bucketName);
        OrderedConsumerContext occ = ctx.createOrderedConsumer(
            new OrderedConsumerConfiguration().filterSubject(filter));

        System.out.printf(OBJ_LINE_FMT_1, bucketName);
        long chunks = 0;
        long items = 0;
        try (IterableConsumer it = occ.iterate()) {
            Message m = it.nextMessage(5000);
            while (m != null) {
                ObjectInfo oi = new ObjectInfo(m);
                if (!oi.isDeleted()) {
                    items++;
                    chunks += oi.getChunks();
                }
                m = it.nextMessage(1000);
            }
            System.out.printf(OBJ_LINE_FMT_2, items, chunks);
        }
        catch (Exception ignore) {
            System.out.printf(OBJ_LINE_FMT_2, -1, -1);
        }
    }

    protected void watchStream(JetStreamManagement jsm, Map<String, Event> watchMap, boolean isEx, String streamName, StreamState ss, java.util.function.Consumer<Void> beforeFirst) {
        Map<String, Long> map = new HashMap<>();
        List<String> sorted = new ArrayList<>();
        for (Subject subject : ss.getSubjects()) {
            sorted.add(subject.getName());
            map.put(subject.getName(), subject.getCount());
        }
        Collections.sort(sorted);

        boolean first = true;
        for (String subject : sorted) {
            try {
                MessageInfo mi = jsm.getLastMessage(streamName, subject);
                if (mi != null) {
                    if (first) {
                        first = false;
                        beforeFirst.accept(null);
                        if (isEx) {
                            System.out.println(EX_TOP_SEP);
                            System.out.println(EX_HEADER);
                            System.out.println(EX_SEP);
                        }
                        else {
                            System.out.println(LOG_TOP_SEP);
                            System.out.println(LOG_HEADER);
                            System.out.println(LOG_SEP_LINE);
                        }
                    }
                    Event prev = watchMap.get(subject);
                    Event event = new Event(mi.getData());
                    watchMap.put(subject, event);
                    String job = (prev == null || !prev.equals(event) ? "* " : "  ") + event.job;
                    if (event.tix != NO_TIX) {
                        job = job + " (" + event.tix + ")";
                    }
                    if (event.qualifier != null) {
                        job = job + " {" + event.qualifier + "}";
                    }

                    String ht = humanTime(event.elapsed);

                    if (isEx) {
                        String time = Debug.rfcTime(mi.getTime());
                        long count = map.get(subject);
                        String deets = event.exceptionMessage == null ? "" : event.exceptionMessage;
                        if (deets.length() > EX_WIDTH) {
                            deets = deets.substring(0, EX_WIDTH - 3) + "...";
                        }
                        System.out.printf(EX_DATA, job, time, count, deets);
                    }
                    else {
                        String cnt = "";
                        if (event.count > 0) {
                            cnt = String.format("%,d", event.count);
                        }
                        System.out.printf(LOG_DATA, job, cnt, ht);
                    }
                }
            }
            catch (Exception e) {
                System.out.println("INTERNAL ERROR: " + e);
            }
        }

        if (!first) {
            System.out.println(isEx ? EX_FOOT : LOG_FOOT_LINE);
        }
    }

    // ----------------------------------------------------------------------------------------------------
    // COMMAND: STREAM
    // ----------------------------------------------------------------------------------------------------
    protected void doStream() throws Exception {
        startJob("Stream");
        String streamName = getStringArgFromPosition(2);
        if (streamName == null || streamName.isEmpty()) {
            exit("Stream not provided");
        }
        doStream(streamName);
    }

    @SuppressWarnings("InfiniteLoopStatement")
    protected void doStream(String streamName) throws IOException, JetStreamApiException, InterruptedException {
        runAdminCommand((nc, jsm) -> {
            StreamInfo si = jsm.getStreamInfo(streamName);
            long seq = si.getStreamState().getFirstSequence();
            seq = getLongArgFromPosition(3, seq);
            long last = si.getStreamState().getLastSequence();
            int tracker = 0;
            while (true) {
                if (seq > last) {
                    si = jsm.getStreamInfo(streamName);
                    long currentLast = si.getStreamState().getLastSequence();
                    last = si.getStreamState().getLastSequence();
                    if (currentLast <= last) {
                        sleep(1000);
                        continue;
                    }
                }
                try {
                    MessageInfo mi = jsm.getNextMessage(streamName, seq, ">");
                    seq = mi.getSeq() + 1;
                    byte[] data = mi.getData();
                    String sdata = "<no data>";
                    if (data != null && data.length > 0) {
                        sdata = new String(data);
                    }
                    if (tracker > 0) {
                        System.out.println();
                    }
                    System.out.println(mi.getSeq() + " | " + mi.getSubject() + " | " + sdata);
                    tracker = 0;
                }
                catch (JetStreamApiException e) {
                    if (e.getMessage().contains("10037")) { // it's fine the message is gone
                        if (++tracker % progressFrequency == 0) {
                            System.out.println();
                        }
                        else {
                            System.out.print('x');
                        }
                    }
                    else {
                        throw e;
                    }
                }
            }
        });
    }

    // ----------------------------------------------------------------------------------------------------
    // WORKER
    // ----------------------------------------------------------------------------------------------------
    protected class WorkState {
        final String workId;
        private final ReentrantLock iLock;
        private final ReentrantLock uLock;
        private long groupCount;
        private long elapsed;
        final long startTime;

        public WorkState() {
            this.workId = generateWorkId();
            this.iLock = new ReentrantLock();
            this.uLock = new ReentrantLock();
            this.groupCount = 0;
            this.startTime = System.currentTimeMillis();
            this.elapsed = 0;
        }

        public long increment() {
            iLock.lock();
            try {
                return ++groupCount;
            }
            finally {
                iLock.unlock();
            }
        }

        public long elapse() {
            uLock.lock();
            try {
                elapsed = System.currentTimeMillis() - startTime;
            }
            finally {
                uLock.unlock();
            }
            return elapsed;
        }

    }

    protected interface SingleThreadedWorker {
        Runnable getWork(Options options, WorkState workState);
    }

    protected interface MultiThreadedWorker {
        Runnable getWork(Options options, int tix, WorkState workState);
    }

    protected void doWorker(String job, SingleThreadedWorker worker) throws InterruptedException {
        startJob(job);
        WorkState ws = new WorkState();
        Thread t = new Thread(worker.getWork(roundRobinOptions().getFirst(), ws));
        t.setName(job);
        t.start();
        t.join();
    }

    protected void doWorker(String job, int threadCount, MultiThreadedWorker worker) throws InterruptedException {
        startJob(job);
        List<Options> optionsList = roundRobinOptions();
        List<Thread> threads = new ArrayList<>(threadCount);
        WorkState ws = new WorkState();
        for (int tix = 0; tix < threadCount; tix++) {
            Thread t = new Thread(worker.getWork(optionsList.get(tix), tix, ws));
            t.setName(job + " " + tix + " ");
            t.start();
            threads.add(t);
        }
        for (Thread t : threads) {
            t.join();
        }
    }

    // ----------------------------------------------------------------------------------------------------
    // GENERAL HELPERS
    // ----------------------------------------------------------------------------------------------------
    protected String generateWorkId() {
        return Long.toHexString(System.currentTimeMillis()).toLowerCase() + NUID.nextGlobalSequence();
    }

    protected String generateName() {
        return NUID.nextGlobalSequence() + "-" + Integer.toHexString(ThreadLocalRandom.current().nextInt()).toLowerCase();
    }

    protected boolean isOsStream(String streamName) {
        return streamName.startsWith(OBJ_STREAM_PREFIX);
    }

    // ----------------------------------------------------------------------------------------------------
    // EVENT
    // ----------------------------------------------------------------------------------------------------
    protected class Event implements JsonSerializable {
        public final String job;
        public final String workId;
        public final int tix;
        public final String qualifier;
        public final boolean defaultQualifier;
        public final long count;
        public final long elapsed;
        public final String exceptionClass;
        public final String exceptionMessage;

        public Event(byte[] jsonBytes) {
            JsonValue jv = JsonParser.parseUnchecked(jsonBytes);
            this.job = JsonValueUtils.readString(jv, "job");
            this.workId = JsonValueUtils.readString(jv, "work_id");
            this.tix = JsonValueUtils.readInteger(jv, "tix", NO_TIX);
            this.qualifier = JsonValueUtils.readString(jv, "qualifier");
            this.defaultQualifier = qualifier == null || qualifier.trim().isEmpty();
            this.count = JsonValueUtils.readLong(jv, "count", 0);
            this.elapsed = JsonValueUtils.readLong(jv, "elapsed", 0);

            this.exceptionClass = JsonValueUtils.readString(jv, "exception_class");
            this.exceptionMessage = JsonValueUtils.readString(jv, "exception_message");
        }

        public Event(String job, String workId, int tix, String qualifier, long count, long elapsed, Exception exception) {
            this.job = job;
            this.workId = workId;
            this.tix = tix;
            this.defaultQualifier = qualifier == null || qualifier.trim().isEmpty();
            if (defaultQualifier) {
                this.qualifier = null;
            }
            else {
                this.qualifier = qualifier.toLowerCase().replace(" ", "").trim();
            }
            this.count = count;
            this.elapsed = elapsed;
            if (exception == null) {
                exceptionClass = null;
                exceptionMessage = null;
            }
            else {
                exceptionClass = exception.getClass().getSimpleName();
                exceptionMessage = exception.getMessage();
            }
        }

        @Override
        public String toJson() {
            JsonValueUtils.MapBuilder mb = JsonValueUtils.mapBuilder();
            mb.put("job", job);
            if (tix != NO_TIX) {
                mb.put("tix", tix);
            }
            mb.put("work_id", workId);
            mb.put("qualifier", qualifier);
            mb.put("count", count);
            mb.put("elapsed", elapsed);
            mb.put("exception_class", exceptionClass);
            mb.put("exception_message", exceptionMessage);
            return mb.jv.toJson();
        }

        @Override
        public String toString() {
            return toJson();
        }

        public Object[] extras(String... messages) {
            List<Object> list = new ArrayList<>();
            if (count > 0) {
                list.add("Count: " + count);
            }
            if (exceptionClass != null) {
                list.add(exceptionClass + ": " + exceptionMessage);
            }
            list.add(humanTime(elapsed));
            if (messages != null) {
                for (String m : messages) {
                    if (m != null) {
                        list.add(m);
                    }
                }
            }
            return list.toArray();
        }

        public String subject() {
            return (exceptionClass == null  ? logSubjectPrefix : exSubjectPrefix)
                + segments(DEFAULT_SEGMENT);
        }

        public String ident() {
            return segments("");
        }

        private String segments(String missing) {
            return job
                // + (workId == null    ? missing : DOT + workId)
                + (defaultQualifier ? missing : DOT + qualifier)
                + (tix == NO_TIX    ? missing : DOT + tix);
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            Event event = (Event) o;
            return tix == event.tix
                && defaultQualifier == event.defaultQualifier && count == event.count && elapsed == event.elapsed && Objects.equals(job, event.job) && Objects.equals(workId, event.workId) && Objects.equals(qualifier, event.qualifier) && Objects.equals(exceptionClass, event.exceptionClass) && Objects.equals(exceptionMessage, event.exceptionMessage);
        }

        @Override
        public int hashCode() {
            int result = Objects.hashCode(job);
            result = 31 * result + Objects.hashCode(workId);
            result = 31 * result + tix;
            result = 31 * result + Objects.hashCode(qualifier);
            result = 31 * result + Boolean.hashCode(defaultQualifier);
            result = 31 * result + Long.hashCode(count);
            result = 31 * result + Long.hashCode(elapsed);
            result = 31 * result + Objects.hashCode(exceptionClass);
            result = 31 * result + Objects.hashCode(exceptionMessage);
            return result;
        }
    }

    // ----------------------------------------------------------------------------------------------------
    // LOG HELPERS
    // ----------------------------------------------------------------------------------------------------
    protected void log(JetStream js, String job, String workId, int tix, long count, long elapsed) {
        Event event = new Event(job, workId, tix, null, count, elapsed, null);
        Debug.info(event.ident(), event.extras());
        publish(js, event);
    }

    protected void log(JetStream js, String job, String workId, int tix, String qualifier, long count, long elapsed) {
        Event event = new Event(job, workId, tix, qualifier, count, elapsed, null);
        Debug.info(event.ident(), event.extras());
        publish(js, event);
    }

    protected void logNoConsole(JetStream js, String job, String workId, int tix, long count, long elapsed) {
        publish(js, new Event(job, workId, tix, null, count, elapsed, null));
    }

    protected void log(JetStream js, String job, String workId, long elapsed, Exception exception) {
        String qualifier = exception.getClass().getSimpleName().replace("Exception", "");
        Event event = new Event(job, workId, NO_TIX, qualifier, 0, elapsed, exception);
        Debug.info(event.ident(), event.extras());
        publish(js, event);
    }

    protected void log(JetStream js, String job, String workId, String qualifier, long elapsed, Exception exception) {
        Event event = new Event(job, workId, NO_TIX, qualifier, 0, elapsed, exception);
        Debug.info(event.ident(), event.extras());
        publish(js, event);
    }

    protected void print(String job, String workId, int tix, String qualifier, long count, long elapsed, String message) {
        Event event = new Event(job, workId, tix, qualifier, count, elapsed, null);
        Debug.info(event.ident(), event.extras(message));
    }

    protected void printConnect(Connection nc, String job, String workId, int tix) {
        print(job, workId, tix, "connect", 0, 0, nc.getServerInfo().getServerId());
    }

    protected void publish(JetStream js, Event event) {
        try {
            js.publish(event.subject(), event.serialize());
        }
        catch (IOException | JetStreamApiException ee) {
            Debug.info("Event Publish Error", event.ident(), event.subject(), ee.getClass().getSimpleName(), ee.getMessage(), event.extras());
        }
    }

    protected void showProgressMaybe(long count, String lineStart) {
        if (count % progressFrequency == 0) {
            System.out.println(" " + count);
            System.out.print(lineStart);
        }
        else {
            System.out.print(DOT);
        }
    }

    protected void endProgress(long count) {
        if (count % progressFrequency != 0) { // last check because I might have already printed this count
            System.out.println(" " + count);
        }
    }

    protected void startProgressJob(String job) {
        System.out.println(workLabel);
        System.out.print(job);
    }

    protected void startJob(String job) {
        System.out.println(workLabel + " - " + job);
    }
}
