/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.nats.client.*;
import io.nats.client.api.RetentionPolicy;
import io.nats.client.api.StreamConfiguration;
import io.nats.client.api.StreamInfo;
import io.nats.client.support.JsonParser;
import io.nats.client.support.JsonSerializable;
import io.nats.client.support.JsonValue;
import io.nats.client.support.JsonValueUtils;
import io.synadia.CommandLine;
import io.synadia.Workload;
import io.synadia.utils.Debug;

import java.io.IOException;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

import static io.nats.client.support.JsonUtils.printFormatted;

@SuppressWarnings("SameParameterValue")
public abstract class AbstractSimWorkload extends Workload {
    protected static final String DATA_STREAM_NAME = "sim-data";
    protected static final String RESULT_STREAM_NAME = "sim-log";
    protected static final String DATA_SUBJECT_PREFIX = "data.";
    protected static final String DATA_STREAM_SUBJECT = DATA_SUBJECT_PREFIX + ">";
    protected static final String RESULT_SUBJECT_PREFIX = "result.";
    protected static final String RESULT_STREAM_SUBJECT = RESULT_SUBJECT_PREFIX + ">";
    protected static final int WORKER_THREAD_COUNT = 3;
    protected static final int NO_TIX = Integer.MIN_VALUE;
    public static final String DEFAULT_SEGMENT = "._";
    public static final String DOT = ".";

    protected final int progressFrequency;

    private Boolean _background;
    protected boolean isBackground() {
        if (_background == null) {
            _background = commandLine.args.contains("background");
        }
        return _background;
    }

    protected AbstractSimWorkload(int progressFrequency) {
        this.progressFrequency = progressFrequency;
    }

    public void aswInit(String defaultLabel, boolean requiresArguments, CommandLine commandLine) {
        init(defaultLabel, commandLine);
        if (requiresArguments && commandLine.args.isEmpty()) {
            exit("Argument(s) Required");
        }
    }

    protected void exit(String reason) {
        Debug.info(workLabel, reason);
        Debug.info(workLabel, "Commands: " + commands());
        System.exit(0);
    }

    protected abstract String commands();

    @SuppressWarnings("SameParameterValue")
    protected void doSetup(Connection nc, long maxMessages) throws IOException, JetStreamApiException {
        printHeader("Setup");
        printHeader("Creating Streams");
        JetStreamManagement jsm = nc.jetStreamManagement();
        safeDeleteStream(jsm, DATA_STREAM_NAME);
        StreamInfo si = jsm.addStream(StreamConfiguration.builder()
            .name(DATA_STREAM_NAME)
            .subjects(DATA_STREAM_SUBJECT)
            .retentionPolicy(RetentionPolicy.WorkQueue)
            .maxMessages(maxMessages)
            .build());
        printFormatted(si.getJv());
        safeDeleteStream(jsm, RESULT_STREAM_NAME);
        si = jsm.addStream(StreamConfiguration.builder()
            .name(RESULT_STREAM_NAME)
            .subjects(RESULT_STREAM_SUBJECT)
            .retentionPolicy(RetentionPolicy.Limits)
            .maxAge(Duration.ofMinutes(5))
            .build());
        printFormatted(si.getJv());
    }

    protected interface Worker {
        Runnable getWork(String job, String runId, int tix, boolean background, AtomicLong groupCount, Options options);
    }

    protected void doWorker(String job, Worker worker) throws InterruptedException {
        boolean background = isBackground();
        printHeader(job, background);
        List<Options> options = roundRobinOptions(WORKER_THREAD_COUNT);
        List<Thread> threads = new ArrayList<>(WORKER_THREAD_COUNT);
        AtomicLong groupCount = new AtomicLong();
        String runId = generateRunId();
        for (int tix = 0; tix < WORKER_THREAD_COUNT; tix++) {
            Thread t = new Thread(worker.getWork(job, runId, tix, background, groupCount, options.get(tix)));
            t.start();
            threads.add(t);
        }
        for (Thread t : threads) {
            t.join();
        }
    }

    protected String generateRunId() {
        return Long.toHexString(System.currentTimeMillis()).toLowerCase();
    }

    protected static class Result implements JsonSerializable {
        public final String job;
        public final String runId;
        public final int tix;
        public final String qualifier;
        public final boolean defaultQualifier;
        public final long count;
        public final long time;
        public final String details;

        public Result(byte[] jsonBytes) {
            JsonValue jv = JsonParser.parseUnchecked(jsonBytes);
            this.job = JsonValueUtils.readString(jv, "job");
            this.runId = JsonValueUtils.readString(jv, "run_id");
            this.tix = JsonValueUtils.readInteger(jv, "tix", NO_TIX);
            this.qualifier = JsonValueUtils.readString(jv, "qualifier");
            this.defaultQualifier = qualifier == null || qualifier.trim().isEmpty();
            this.count = JsonValueUtils.readLong(jv, "count", 0);
            this.time = JsonValueUtils.readLong(jv, "time", 0);
            this.details = JsonValueUtils.readString(jv, "details");
        }

        public Result(String job, String runId, int tix, String qualifier, long count, Object details) {
            this.job = job;
            this.runId = runId;
            this.tix = tix;
            this.defaultQualifier = qualifier == null || qualifier.trim().isEmpty();
            if (defaultQualifier) {
                this.qualifier = null;
            }
            else {
                this.qualifier = qualifier.toLowerCase().replace(" ", "").trim();
            }
            this.count = count;
            this.time = System.currentTimeMillis();
            String temp = details == null ? null : details.toString().trim();
            this.details = temp == null || temp.isEmpty() ? null : temp;
        }

        @Override
        public String toJson() {
            JsonValueUtils.MapBuilder mb = JsonValueUtils.mapBuilder();
            mb.put("job", job);
            if (tix != NO_TIX) {
                mb.put("tix", tix);
            }
            mb.put("run_id", runId);
            mb.put("qualifier", qualifier);
            mb.put("count", count);
            mb.put("time", time);
            mb.put("details", details);
            return mb.jv.toJson();
        }

        @Override
        public String toString() {
            StringBuilder sb = new StringBuilder(ident());
            if (count > 0) {
                sb.append(" Count:").append(count);
            }
            if (details != null) {
                if (count > 0) {
                    sb.append(" | ");
                }
                sb.append(details);
            }
            return sb.toString();
        }

        public String ident() {
            return "[" + time + "] [" + segments().replace(DEFAULT_SEGMENT, "") + "]";
        }

        public String subject() {
            return RESULT_SUBJECT_PREFIX + segments();
        }

        private String segments() {
            return job + DOT + runId
                + (defaultQualifier ? DEFAULT_SEGMENT : DOT + qualifier)
                + (tix == NO_TIX    ? DEFAULT_SEGMENT : DOT + tix);
        }
    }

    protected void autoProgress(boolean background, JetStream js, String job, String runId, long count, Object details) {
        showProgressMaybe(background, count);
        publishResult(js, job, runId, NO_TIX, null, count, details);
    }

    protected void autoResult(boolean background, JetStream js, String job, String runId, long count, Object details) {
        Result result = new Result(job, runId, NO_TIX, null, count, details);
        if (!background) {
            System.out.println(result);
        }
        publishResult(js, result);
    }

    protected void print(boolean background, String job, String runId, int tix, String qualifier, long count, Object details) {
        if (!background) {
            System.out.println(new Result(job, runId, tix, qualifier, count, details));
        }
    }

    protected void autoException(boolean background, JetStream js, String job, String runId, int tix, long count, Exception ex) {
        Result result = new Result(job, runId, tix, ex.getClass().getSimpleName(), count, ex);
        if (!background) {
            System.out.println(result);
        }
        publishResult(js, result);
    }

    protected void publishResult(JetStream js, String job, String runId, int tix, String qualifier, long count, Object details) {
        publishResult(js, new Result(job, runId, tix, qualifier, count, details));
    }

    protected void publishResult(JetStream js, Result result) {
        try {
            js.publish(result.subject(), result.serialize());
        }
        catch (IOException | JetStreamApiException ee) {
            System.err.println(result.ident() + " Result Publish Error | " + ee);
        }
    }

    protected void showProgressMaybe(boolean background, long count) {
        if (!background) {
            System.out.print(DOT);
            if (count % progressFrequency == 0) {
                System.out.println(count);
            }
        }
    }

    protected void print(boolean background, String message) {
        if (!background) {
            System.out.println(System.lineSeparator() + message);
        }
    }

    protected void endProgress(boolean background, long count) {
        if (!background && count % progressFrequency != 0) { // last check because I might have already printed this count
            System.out.println(count);
        }
    }

    protected void printHeader(String job) {
        System.out.println(workLabel + " - " + job);
    }

    protected void printHeader(String job, boolean background) {
        System.out.println(workLabel + " - " + job + " (background=" + background + ")");
    }
}
