/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.nats.client.*;
import io.nats.client.support.JsonParser;
import io.nats.client.support.JsonValue;
import io.nats.client.support.JsonValueUtils;
import io.nats.jsmulti.shared.ProfileStats;
import io.synadia.CommandLine;
import io.synadia.Workload;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.DateAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYItemRenderer;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.chart.ui.ApplicationFrame;
import org.jfree.chart.ui.RectangleInsets;
import org.jfree.chart.ui.UIUtils;
import org.jfree.data.time.FixedMillisecond;
import org.jfree.data.time.TimeSeries;
import org.jfree.data.time.TimeSeriesCollection;

import javax.swing.*;
import java.awt.*;
import java.text.SimpleDateFormat;

import static io.synadia.utils.Constants.TIME_MS;

public class ChartProfile extends Workload {
    final String filter;
    public ChartProfile(CommandLine commandLine) {
        super("Chart Profile", commandLine);

        if (commandLine.args.size() != 1) {
            throw new RuntimeException("Filter Required");
        }
        filter = commandLine.args.getFirst();
    }

    @Override
    public void runWorkload() throws Exception {
        long firstTime = -1;
        TimeSeries al = new TimeSeries("Allocated");
        TimeSeries fm = new TimeSeries("Free Memory");
        TimeSeries hu = new TimeSeries("Heap Used");
        Options adminOpts = getAdminOptions();
        try (Connection sourceNc = Nats.connect(adminOpts))
        {
            JetStream js = sourceNc.jetStream();
            JetStreamSubscription sub = js.subscribe(
                params.profileStreamSubject,
                PushSubscribeOptions.builder().ordered(true).build());
            Thread.sleep(1000); // so I don't have to wait for messages
            Message m = sub.nextMessage(1000);
            while (m != null) {
                String s = m.getSubject();
                if (s.contains(filter)) {
                    JsonValue jv = JsonParser.parse(m.getData());
                    long timeMs = JsonValueUtils.readLong(jv, TIME_MS, -1);
                    if (firstTime == -1) {
                        firstTime = timeMs;
                    }
                    ProfileStats ps = new ProfileStats(jv);
                    FixedMillisecond fixed = new FixedMillisecond(timeMs);
                    al.add(fixed, mb(ps.allocatedMemory));
                    fm.add(fixed, mb(ps.freeMemory));
                    hu.add(fixed, mb(ps.heapUsed));
                }
                m = sub.nextMessage(100);
            }
        }

        TimeSeriesCollection dataset = new TimeSeriesCollection();
        dataset.addSeries(al);
        dataset.addSeries(fm);
        dataset.addSeries(hu);

        JFreeChart chart = ChartFactory.createTimeSeriesChart(
            "Memory Allocation", // title
            "Time",              // x-axis label
            "Memory (mb)",       // y-axis label
            dataset);
        chart.setBackgroundPaint(Color.WHITE);

        XYPlot plot = (XYPlot) chart.getPlot();
        plot.setBackgroundPaint(Color.LIGHT_GRAY);
        plot.setDomainGridlinePaint(Color.WHITE);
        plot.setRangeGridlinePaint(Color.WHITE);
        plot.setAxisOffset(new RectangleInsets(5.0, 5.0, 5.0, 5.0));
        plot.setDomainCrosshairVisible(true);
        plot.setRangeCrosshairVisible(true);

        XYItemRenderer r = plot.getRenderer();
        if (r instanceof XYLineAndShapeRenderer renderer) {
            renderer.setDefaultShapesVisible(true);
            renderer.setDefaultShapesFilled(true);
            renderer.setDrawSeriesLineAsPath(true);
        }

        DateAxis axis = (DateAxis) plot.getDomainAxis();
        axis.setDateFormatOverride(new SimpleDateFormat("MMM-yyyy"));

        ChartPanel panel = new ChartPanel(chart, false);
        panel.setFillZoomRectangle(true);
        panel.setMouseWheelEnabled(true);

        ApplicationFrame af = new ApplicationFrame("Profile for " + filter);
        panel.setPreferredSize(new java.awt.Dimension(1500, 800));
        af.setContentPane(panel);
        af.pack();
        UIUtils.centerFrameOnScreen(af);
        af.setVisible(true);
        af.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        Thread.sleep(1_000_000);
    }

    public double mb(long bytes) {
        return (double) bytes / 1024 / 1024;
    }
}
