/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.nats.client.*;
import io.nats.client.api.*;
import io.synadia.CommandLine;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

import static io.nats.jsmulti.shared.Utils.sleep;

public class ConsumerInfoSim extends AbstractSimWorkload {
    public static final String CONSUMER_PREFIX = "sim-con-";
    public static final int CONSUMER_COUNT = 10000;
    public static final long PUBLISH_JITTER = 250;
    public static final long CONSUME_JITTER = 500;
    public static final int INFO_THREAD_COUNT = 8;
    public static final int PROGRESS_FREQUENCY = 100;
    public static final long RESULTS_FREQUENCY = 5000;
    public static final int INFO_REPORT_FREQUENCY = 10000;
    public static final long SEED_MESSAGES = 300_000;
    public static final long MAX_MESSAGES = 1_000_000;

    public ConsumerInfoSim() {
        super(PROGRESS_FREQUENCY);
    }

    @Override
    public void init(CommandLine commandLine) {
        aswInit("Consumer Info Sim", true, commandLine);
    }

    @Override
    protected String commands() {
        return "'setup', 'create', 'list', 'clear', 'publish', 'consume', 'info', 'results'";
    }

    @Override
    public void runWorkload() throws Exception {
        try (Connection nc = Nats.connect(getAdminOptions())) {
            String arg = commandLine.args.getFirst();
            switch (arg) {
                case "setup"   -> doSetup(nc);
                case "create"  -> doCreateConsumers(nc);
                case "list"    -> doList(nc);
                case "clear"   -> doClear(nc);
                case "publish" -> doWorker("Publish", this::publishWorker);
                case "consume" -> doWorker("Consume", this::consumeWorker);
                case "info"    -> doInfo();
                case "results" -> doResults(nc);
                default        -> exit("Unknown custom workload");
            }
        }
    }

    protected void doSetup(Connection nc) throws IOException, JetStreamApiException {
        super.doSetup(nc, MAX_MESSAGES);
        doCreateConsumers(nc);
    }

    private void doCreateConsumers(Connection nc) throws IOException, JetStreamApiException {
        printHeader("Creating Consumers");
        JetStreamManagement jsm = nc.jetStreamManagement();
        long count = 0;
        for (int cx = 0; cx < CONSUMER_COUNT; cx++) {
            jsm.createConsumer(DATA_STREAM_NAME, ConsumerConfiguration.builder()
                .durable(toConsumerName(cx))
                .filterSubject(toSubjectName(cx))
                .build());
            showProgressMaybe(false, ++count);
        }
        endProgress(false, count);
        List<String> list = jsm.getConsumerNames(DATA_STREAM_NAME);
        System.out.println(list.size());
    }

    private void doList(Connection nc) throws IOException, JetStreamApiException {
        printHeader("List Consumers");
        JetStreamManagement jsm = nc.jetStreamManagement();
        List<String> list = jsm.getConsumerNames(DATA_STREAM_NAME);
        list.forEach(System.out::println);
        System.out.println(list.size());
    }

    private void doClear(Connection nc) throws IOException, JetStreamApiException {
        printHeader("Clear Consumers");
        JetStreamManagement jsm = nc.jetStreamManagement();
        List<String> list = jsm.getConsumerNames(DATA_STREAM_NAME);
        int index = 0;
        while (index < list.size()) {
            String cn = list.get(index);
            jsm.deleteConsumer(DATA_STREAM_NAME, cn);
            showProgressMaybe(false, ++index);
        }
        endProgress(false, index);
    }

    @SuppressWarnings("InfiniteLoopStatement")
    private Runnable publishWorker(String job, String runId, int tix, boolean background, AtomicLong groupCount, Options options) {
        return () -> {
            try (Connection nc = Nats.connect(options)) {
                JetStream js = nc.jetStream();
                printResult(background, job, runId, tix, "connect", 0, nc.getServerInfo().getServerId());
                List<Integer> consumers = new ArrayList<>();
                for (int cx = 0; cx < CONSUMER_COUNT; cx++) {
                    consumers.add(cx);
                }
                long ioEx = 0;
                long jsapiEx = 0;
                while (true) {
                    Collections.shuffle(consumers);
                    for (Integer cx : consumers) {
                        if (groupCount.get() > SEED_MESSAGES) {
                            jitter(PUBLISH_JITTER);
                        }
                        try {
                            js.publish(toSubjectName(cx), null);
                            autoProgress(background, js, job, runId, NO_TIX, "publish", groupCount.incrementAndGet(), null);
                        }
                        catch (IOException ie) {
                            autoException(background, js, job, runId, tix, ++ioEx, ie);
                        }
                        catch (JetStreamApiException e) {
                            autoException(background, js, job, runId, tix, ++jsapiEx, e);
                        }
                    }
                    endProgress(background, groupCount.get());
                }
            }
            catch (InterruptedException | IOException e) {
                throw new RuntimeException(e);
            }
        };
    }

    @SuppressWarnings("InfiniteLoopStatement")
    private Runnable consumeWorker(String job, String runId, int tix, boolean background, AtomicLong groupCount, Options options) {
        return () -> {
            try (Connection nc = Nats.connect(options)) {
                JetStream js = nc.jetStream();
                printResult(background, job, runId, tix, "connect", 0, nc.getServerInfo().getServerId());

                List<Integer> consumers = new ArrayList<>();
                for (int cx = 0; cx < CONSUMER_COUNT; cx++) {
                    consumers.add(cx);
                }
                StreamContext sctx = nc.getStreamContext(DATA_STREAM_NAME);

                while (true) {
                    Collections.shuffle(consumers);
                    for (Integer cx : consumers) {
                        jitter(CONSUME_JITTER);
                        ConsumerContext cctx = sctx.getConsumerContext(toConsumerName(cx));
                        try (FetchConsumer fc = cctx.fetch(FetchConsumeOptions.builder().maxMessages(1).build())) {
                            Message m = fc.nextMessage();
                            if (m != null) {
                                m.ack();
                            }
                            autoProgress(background, js, job, runId, NO_TIX, "consume", groupCount.incrementAndGet(), null);
                        }
                        catch (Exception ignore) {}
                    }
                    if (!background) {
                        endProgress(background, groupCount.get());
                    }
                }
            }
            catch (IOException | InterruptedException | JetStreamApiException e) {
                throw new RuntimeException(e);
            }
        };
    }

    @SuppressWarnings("InfiniteLoopStatement")
    private void doResults(Connection nc) throws IOException {
        printHeader("Results");
        JetStreamManagement jsm = nc.jetStreamManagement();
        while (true) {
            try {
                System.out.println();
                System.out.println("----------------------------------------------------------------------------------------------------");
                StreamInfo si = jsm.getStreamInfo(RESULT_STREAM_NAME, StreamInfoOptions.allSubjects());
                for (Subject subject : si.getStreamState().getSubjects()) {
                    MessageInfo mi = jsm.getLastMessage(RESULT_STREAM_NAME, subject.getName());
                    if (mi != null) {
                        Result result = new Result(mi.getData());
                        System.out.println(result);
                    }
                }
                System.out.println("----------------------------------------------------------------------------------------------------");
                sleep(RESULTS_FREQUENCY);
            }
            catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
    }

    private void doInfo() throws InterruptedException {
        boolean background = isBackground();
        printHeader("Info", background);
        List<Options> options = roundRobinOptions(INFO_THREAD_COUNT);
        List<Thread> threads = new ArrayList<>(INFO_THREAD_COUNT);
        List<List<String>> cnLists = new ArrayList<>();
        for (int t = 0; t < INFO_THREAD_COUNT; t++) {
            List<String> list = new ArrayList<>();
            cnLists.add(list);
        }
        int tix = INFO_THREAD_COUNT - 1;
        for (int cx = 0; cx < CONSUMER_COUNT; cx++) {
            if (++tix == INFO_THREAD_COUNT) {
                tix = 0;
            }
            List<String> list = cnLists.get(tix);
            list.add(toConsumerName(cx));
        }

        AtomicLong groupCount = new AtomicLong();
        String runId = generateRunId();
        for (tix = 0; tix < INFO_THREAD_COUNT; tix++) {
            Runnable infoWorker = infoWorker(runId, tix, background, groupCount, options.get(tix), cnLists.get(tix));
            Thread t = new Thread(infoWorker);
            t.start();
            threads.add(t);
        }

        for (Thread t : threads) {
            t.join();
        }
    }

    static String INFO_JOB = "Consumer Info";

    @SuppressWarnings("InfiniteLoopStatement")
    private Runnable infoWorker(String runId, int tix, boolean background, AtomicLong groupCount, Options options, List<String> consumerNames) {
        return () -> {
            try (Connection nc = Nats.connect(options)) {
                JetStreamManagement jsm = nc.jetStreamManagement();
                JetStream js = nc.jetStream();
                printResult(background, INFO_JOB, runId, tix, "connect", 0, nc.getServerInfo().getServerId());
                List<String> list = new ArrayList<>(consumerNames);
                Collections.shuffle(list);
                long ioEx = 0;
                long jsapiEx = 0;
                while (true) {
                    for (String consumerName : list) {
                        try {
                            jsm.getConsumerInfo(DATA_STREAM_NAME, consumerName);
                            long gc = groupCount.incrementAndGet();
                            if (gc % INFO_REPORT_FREQUENCY == 0) {
                                autoResult(background, js, INFO_JOB, runId, NO_TIX, "get", gc, null);
                            }
                        }
                        catch (IOException ie) {
                            autoException(background, js, INFO_JOB, runId, tix, ++ioEx, ie);
                        }
                        catch (JetStreamApiException je) {
                            autoException(background, js, INFO_JOB, runId, tix, ++jsapiEx, je);
                        }
                    }
                }
            }
            catch (IOException | InterruptedException e) {
                throw new RuntimeException(e);
            }
        };
    }

    private static String toSubjectName(int cx) {
        return DATA_SUBJECT_PREFIX + cx;
    }

    private static String toConsumerName(int x) {
        return CONSUMER_PREFIX + x;
    }
}
