/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.nats.client.*;
import io.nats.client.api.*;
import io.nats.client.support.JsonParser;
import io.nats.client.support.JsonSerializable;
import io.nats.client.support.JsonValue;
import io.nats.client.support.JsonValueUtils;
import io.synadia.CommandLine;
import io.synadia.utils.Debug;

import java.io.IOException;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

import static io.nats.client.support.JsonUtils.printFormatted;

public class ConsumerInfoSim extends AbstractCustomWorkload {
    protected String dataStreamName;
    protected String dataSubjectPrefix;
    protected String dataStreamSubject;
    protected long dataMaxMessages;

    protected String queueStreamName;
    protected String queueSubject;
    protected String queueConsumerName;
    protected long queueMaxMessages;

    private int maxConsumers;

    private String produceJob;
    private int produceThreadCount;
    private long produceReportFrequency;
    private long produceJitter;
    private long produceFullJitter;
    private int produceMessageMin;
    private int produceMessageMax;

    private String consumeJob;
    private int consumeThreadCount;
    private int consumeBatch;
    private long consumeReportFrequency;
    private long consumeJitter;

    private String infoJob;
    private int infoThreadCount;
    private long infoReportFrequency;
    private long infoJitter;

    @Override
    public void init(CommandLine commandLine) {
        customWorkloadInit("Consumer Info Sim", true, commandLine);

        dataStreamName = JsonValueUtils.readString(params.jv, "data_stream_name", "data");
        dataSubjectPrefix = JsonValueUtils.readString(params.jv, "data_subject_prefix", "data.");
        dataStreamSubject = JsonValueUtils.readString(params.jv, "data_stream_subject", "data.>");
        dataMaxMessages = JsonValueUtils.readLong(params.jv, "data_max_messages", 1_000_000);

        queueStreamName = JsonValueUtils.readString(params.jv, "queue_stream_name", "queue");
        queueSubject = JsonValueUtils.readString(params.jv, "queue_subject", "qsub");
        queueConsumerName = JsonValueUtils.readString(params.jv, "queue_consumer_name", "qcon");
        queueMaxMessages = JsonValueUtils.readLong(params.jv, "queue_max_messages", 1_000_000);

        maxConsumers = JsonValueUtils.readInteger(params.jv, "max_consumers", 10_000);

        produceJob = JsonValueUtils.readString(params.jv, "produce_job", "Produce");
        produceThreadCount = JsonValueUtils.readInteger(params.jv, "produce_thread_count", 3);
        produceReportFrequency = JsonValueUtils.readLong(params.jv, "produce_report_frequency", 100);
        produceJitter = JsonValueUtils.readLong(params.jv, "produce_jitter", 50);
        produceFullJitter = JsonValueUtils.readLong(params.jv, "produce_full_jitter", 1000);
        produceMessageMin = JsonValueUtils.readInteger(params.jv, "produce_message_min", 10);
        produceMessageMax = JsonValueUtils.readInteger(params.jv, "produce_message_max", 100);

        consumeJob = JsonValueUtils.readString(params.jv, "consume_job", "Consume");
        consumeThreadCount = JsonValueUtils.readInteger(params.jv, "consume_thread_count", 3);
        consumeBatch = JsonValueUtils.readInteger(params.jv, "consume_batch", 10);
        consumeJitter = JsonValueUtils.readLong(params.jv, "consume_jitter", 250);
        consumeReportFrequency = JsonValueUtils.readLong(params.jv, "consume_report_frequency", 100);

        infoJob = JsonValueUtils.readString(params.jv, "info_job", "Info");
        infoThreadCount = JsonValueUtils.readInteger(params.jv, "info_thread_count", 8);
        infoReportFrequency = JsonValueUtils.readLong(params.jv, "info_report_frequency", 1000);
        infoJitter = JsonValueUtils.readLong(params.jv, "info_jitter", 10_000);

        Debug.info(workLabel, "dataStreamName", dataStreamName);
        Debug.info(workLabel, "dataSubjectPrefix", dataSubjectPrefix);
        Debug.info(workLabel, "dataStreamSubject", dataStreamSubject);
        Debug.info(workLabel, "dataMaxMessages", dataMaxMessages);

        Debug.info(workLabel, "queueStreamName", queueStreamName);
        Debug.info(workLabel, "queueSubject", queueSubject);
        Debug.info(workLabel, "queueConsumerName", queueConsumerName);
        Debug.info(workLabel, "queueMaxMessages", queueMaxMessages);

        Debug.info(workLabel, "maxConsumers", maxConsumers);

        Debug.info(workLabel, "produceJob", produceJob);
        Debug.info(workLabel, "produceThreadCount", produceThreadCount);
        Debug.info(workLabel, "produceReportFrequency", produceReportFrequency);
        Debug.info(workLabel, "produceJitter", produceJitter);
        Debug.info(workLabel, "produceFullJitter", produceFullJitter);
        Debug.info(workLabel, "produceMessageMin", produceMessageMin);
        Debug.info(workLabel, "produceMessageMax", produceMessageMax);

        Debug.info(workLabel, "consumeJob", consumeJob);
        Debug.info(workLabel, "consumeThreadCount", consumeThreadCount);
        Debug.info(workLabel, "consumeBatch", consumeBatch);
        Debug.info(workLabel, "consumeReportFrequency", consumeReportFrequency);
        Debug.info(workLabel, "consumeJitter", consumeJitter);

        Debug.info(workLabel, "infoJob", infoJob);
        Debug.info(workLabel, "infoThreadCount", infoThreadCount);
        Debug.info(workLabel, "infoReportFrequency", infoReportFrequency);
        Debug.info(workLabel, "infoJitter", infoJitter);
    }

    @Override
    protected String[] commands() {
        return new String[] {"setup", "list", "produce", "consume", "info", "watch", "stream", "clear consumers|data|queue|log|ex", "purge <job>"};
    }

    @Override
    public void runWorkload() throws Exception {
        try (Connection nc = Nats.connect(getAdminOptions())) {
            String arg = commandLine.args.getFirst();
            switch (arg) {
                case "setup"   -> doSetup(nc);
                case "list"    -> doList(nc);
                case "produce" -> doWorker(produceJob, produceThreadCount, this::produceWorker);
                case "consume" -> doWorker(consumeJob, consumeThreadCount, this::consumeWorker);
                case "info"    -> doWorker(infoJob, infoThreadCount, this::infoWorker);
                case "watch"   -> doWatch(nc, dataStreamName, queueStreamName);
                case "stream"  -> doStream(nc);
                case "clear"   -> doClear(nc);
                case "purge"   -> doPurge(nc);
                default        -> exit("Unknown custom workload");
            }
        }
    }

    protected void doSetup(Connection nc) throws IOException, JetStreamApiException {
        JetStreamManagement jsm = nc.jetStreamManagement();
        super.doSetup(jsm);

        StreamInfo si = jsm.addStream(StreamConfiguration.builder()
            .name(dataStreamName)
            .subjects(dataStreamSubject)
            .retentionPolicy(RetentionPolicy.WorkQueue)
            .maxMessages(dataMaxMessages)
            .build());
        printFormatted(si.getJv());

        si = jsm.addStream(StreamConfiguration.builder()
            .name(queueStreamName)
            .subjects(queueSubject)
            .retentionPolicy(RetentionPolicy.WorkQueue)
            .maxMessages(queueMaxMessages)
            .build());
        printFormatted(si.getJv());

        jsm.createConsumer(queueStreamName, ConsumerConfiguration.builder().durable(queueConsumerName).filterSubject(queueSubject).build());
    }

    private void doList(Connection nc) throws IOException, JetStreamApiException {
        startProgressJob("List Consumers");
        JetStreamManagement jsm = nc.jetStreamManagement();
        List<String> consumerNames = jsm.getConsumerNames(dataStreamName);
        consumerNames.forEach(cn -> System.out.println("Consumer: " + cn));
        System.out.println("Total: " + consumerNames.size());
    }

    private void doClear(Connection nc) throws IOException, JetStreamApiException {
        String option = getStringArgFromPosition(2);
        if (option == null || option.isEmpty()) {
            exit("Clear option not provided");
            return;
        }
        switch (option) {
            case "consumers" -> {
                startProgressJob("Clear Consumers");
                JetStreamManagement jsm = nc.jetStreamManagement();
                List<String> list = jsm.getConsumerNames(dataStreamName);
                int index = 0;
                while (index < list.size()) {
                    String cn = list.get(index);
                    jsm.deleteConsumer(dataStreamName, cn);
                    showProgressMaybe(++index, "Clear Consumers");
                }
                endProgress(index);
            }
            case "data" -> doClearData(nc);
            case "queue" -> doClearQueue(nc);
            case "log" -> doClearLog(nc);
            case "ex" -> doClearExceptions(nc);
            default -> exit("Unknown clear option: '" + option + "'");
        }
    }

    protected void doClearData(Connection nc) throws IOException, JetStreamApiException {
        startJob("Clear Data");
        nc.jetStreamManagement().purgeStream(dataStreamName);
    }

    protected void doClearQueue(Connection nc) throws IOException, JetStreamApiException {
        startJob("Clear Queue");
        nc.jetStreamManagement().purgeStream(dataStreamName);
    }

    private void doPurge(Connection nc) throws IOException, JetStreamApiException {
        String code = getStringArgFromPosition(2);
        if (code == null || code.isEmpty()) {
            exit("Purge option not provided");
        }
        else {
            JetStreamManagement jsm = nc.jetStreamManagement();
            String purge = logSubjectPrefix + code + ".>";
            startProgressJob("Purge: " + code + "(" + purge + ")");
            jsm.purgeStream(logStreamName, PurgeOptions.builder().subject(purge).build());
        }
    }

    private void printConnect(Connection nc, String job, String workId, int tix) {
        print(job, workId, tix, "connect", 0, 0, nc.getServerInfo().getServerId());
    }

    static class QueueData implements JsonSerializable {
        public final String consumerName;
        public final String dataSubject;
        public final int messageCount;

        @Override
        public String toString() {
            return "QueueData{" +
                "consumerName='" + consumerName + '\'' +
                ", dataSubject='" + dataSubject + '\'' +
                ", messageCount=" + messageCount +
                '}';
        }

        public QueueData(String consumerName, String dataSubject, int messageCount) {
            this.consumerName = consumerName;
            this.dataSubject = dataSubject;
            this.messageCount = messageCount;
        }

        public QueueData(byte[] jsonBytes) {
            JsonValue jv = JsonParser.parseUnchecked(jsonBytes);
            this.consumerName = JsonValueUtils.readString(jv, "consumer_name");
            this.dataSubject = JsonValueUtils.readString(jv, "data_subject");
            this.messageCount = JsonValueUtils.readInteger(jv, "message_count", 0);
        }

        @Override
        public String toJson() {
            JsonValueUtils.MapBuilder mb = JsonValueUtils.mapBuilder();
            mb.put("consumer_name", consumerName);
            mb.put("data_subject", dataSubject);
            mb.put("message_count", messageCount);
            return mb.jv.toJson();
        }
    }

    @SuppressWarnings("InfiniteLoopStatement")
    private Runnable produceWorker(Options options, int tix, WorkState ws) {
        return () -> {
            try (Connection nc = Nats.connect(options)) {
                JetStreamManagement jsm = nc.jetStreamManagement();
                JetStream js = nc.jetStream();
                printConnect(nc, produceJob, ws.workId, tix);
                jitter(produceJitter / 10);
                int cutoff = maxConsumers;
                while (true) {
                    try {
                        StreamInfo si = jsm.getStreamInfo(dataStreamName);
                        long siCount = si.getStreamState().getConsumerCount();
                        if (siCount >= cutoff) {
                            if (cutoff == maxConsumers) {
                                cutoff = maxConsumers * 10 / 100; // 10 percent
                                print(produceJob, ws.workId, tix, null, 0, ws.elapse(), "* System is full. " + siCount + "/" + maxConsumers);
                            }
                        }
                        else {
                            cutoff = maxConsumers;
                            String consumerName = generateConsumerName();
                            String dataSubject = toDataSubject(consumerName);
                            int messageCount = ThreadLocalRandom.current().nextInt(produceMessageMin, produceMessageMax + 1);

                            // 1. create the consumer
                            jsm.createConsumer(dataStreamName, ConsumerConfiguration.builder()
                                .durable(consumerName)
                                .filterSubject(dataSubject)
                                .build());

                            // 2. publish messages
                            for (int i = 0; i < messageCount; i++) {
                                js.publish(dataSubject, null);
                            }

                            // 3. put a record in the queue last so it's not used until messages are published
                            js.publish(queueSubject, new QueueData(consumerName, dataSubject, messageCount).serialize());
                            
                            long count = ws.increment();
                            if (count % produceReportFrequency == 0) {
                                log(js, produceJob, ws.workId, NO_TIX, count, ws.elapse());
                            }
                        }
                    }
                    catch (IOException | JetStreamApiException e) {
                        log(js, produceJob, ws.workId, ws.elapse(), e);
                    }
                    jitter(produceFullJitter);
                }
            }
            catch (InterruptedException | IOException e) {
                throw new RuntimeException(e);
            }
        };
    }

    @SuppressWarnings("InfiniteLoopStatement")
    private Runnable consumeWorker(Options options, int tix, WorkState ws) {
        return () -> {
            try (Connection nc = Nats.connect(options)) {
                JetStreamManagement jsm = nc.jetStreamManagement();
                JetStream js = nc.jetStream();
                printConnect(nc, consumeJob, ws.workId, tix);
                jitter(consumeJitter / 10);
                ConsumerContext qConsumerCtx = nc.getConsumerContext(queueStreamName, queueConsumerName);
                while (true) {
                    try {
                        QueueData qd = queueNext(qConsumerCtx);
                        if (qd != null) {
                            StreamContext sctx = nc.getStreamContext(dataStreamName);
                            ConsumerContext cctx = sctx.getConsumerContext(qd.consumerName);
                            try (FetchConsumer fc = cctx.fetch(FetchConsumeOptions.builder().maxMessages(consumeBatch).noWait().build())) {
                                Message m = fc.nextMessage();
                                while (m != null) {
                                    m.ack();
                                    m = fc.nextMessage();
                                }
                                long count = ws.increment();
                                if (count % consumeReportFrequency == 0) {
                                    log(js, consumeJob, ws.workId, NO_TIX, count, ws.elapse());
                                }
                            }
                            catch (IOException | JetStreamApiException e) {
                                log(js, consumeJob, ws.workId, ws.elapse(), e);
                            }
                            finally {
                                try {
                                    jsm.deleteConsumer(dataStreamName, qd.consumerName);
                                }
                                catch (Exception ignore) {}
                                try {
                                    jsm.purgeStream(dataStreamName, PurgeOptions.subject(qd.dataSubject));
                                }
                                catch (Exception ignore) {}
                            }
                        }
                    }
                    catch (Exception ignore) {}
                    jitter(consumeJitter);
                }
            }
            catch (IOException | InterruptedException | JetStreamApiException e) {
                throw new RuntimeException(e);
            }
        };
    }

    private QueueData queueNext(ConsumerContext qConsumerCtx) throws JetStreamApiException, IOException, InterruptedException, JetStreamStatusCheckedException {
        Message qm = qConsumerCtx.next(1000);
        if (qm != null) {
            qm.ack();
            return new QueueData(qm.getData());
        }
        return null;
    }

    @SuppressWarnings("InfiniteLoopStatement")
    private Runnable infoWorker(Options options, int tix, WorkState ws) {
        return () -> {
            try (Connection nc = Nats.connect(options)) {
                JetStreamManagement jsm = nc.jetStreamManagement();
                JetStream js = nc.jetStream();
                printConnect(nc, infoJob, ws.workId, tix);
                jitter(infoJitter / 10);
                long ownCount = 0;
                while (true) {
                    List<String> consumerNames = jsm.getConsumerNames(dataStreamName);
                    Collections.shuffle(consumerNames);
                    for (String consumerName : consumerNames) {
                        try {
                            jsm.getConsumerInfo(dataStreamName, consumerName);
                            long groupCount = ws.increment();
                            if (groupCount % infoReportFrequency == 0) {
                                log(js, infoJob, ws.workId, NO_TIX, groupCount, ws.elapse());
                            }
                            if (++ownCount % infoReportFrequency == 0) {
                                log(js, infoJob, ws.workId, tix, ownCount, ws.elapse());
                            }
                        }
                        catch (IOException | JetStreamApiException e) {
                            if (!e.getMessage().contains("10014")) { // it's fine the consumer is missing
                                log(js, infoJob, ws.workId, ws.elapse(), e);
                            }
                        }
                    }
                    jitter(infoJitter);
                }
            }
            catch (IOException | InterruptedException | JetStreamApiException e) {
                throw new RuntimeException(e);
            }
        };
    }

    private String toDataSubject(String consumerName) {
        return dataSubjectPrefix + consumerName;
    }

    private String generateConsumerName() {
        return NUID.nextGlobalSequence() + "-" + Integer.toHexString(ThreadLocalRandom.current().nextInt()).toLowerCase();
    }

    @SuppressWarnings("InfiniteLoopStatement")
    protected void doStream(Connection nc) throws Exception {
        startJob("Stream");
        String streamName = getStringArgFromPosition(2);
        if (streamName == null || streamName.isEmpty()) {
            exit("Stream not provided");
        }
        JetStreamManagement jsm = nc.jetStreamManagement();
        StreamInfo si = jsm.getStreamInfo(streamName);
        long seq = si.getStreamState().getFirstSequence();
        seq = getLongArgFromPosition(3, seq);
        long last = si.getStreamState().getLastSequence();
        int tracker = 0;
        while (true) {
            if (seq > last) {
                si = jsm.getStreamInfo(streamName);
                long currentLast = si.getStreamState().getLastSequence();
                last = si.getStreamState().getLastSequence();
                if (currentLast <= last) {
                    Thread.sleep(1000);
                    continue;
                }
            }
            try {
                MessageInfo mi = jsm.getNextMessage(streamName, seq, ">");
                seq = mi.getSeq() + 1;
                byte[] data = mi.getData();
                String sdata = "<no data>";
                if (data != null && data.length > 0) {
                    sdata = new String(data);
                }
                if (tracker > 0) {
                    System.out.println();
                }
                System.out.println(mi.getSeq() + " | " + mi.getSubject() + " | " + sdata);
                tracker = 0;
            }
            catch (JetStreamApiException e) {
                if (e.getMessage().contains("10037")) { // it's fine the message is gone
                    if (++tracker % progressFrequency == 0) {
                        System.out.println();
                    }
                    else {
                        System.out.print('x');
                    }
                }
                else {
                    throw e;
                }
            }
        }
    }
}
