/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.nats.client.*;
import io.nats.client.api.ConsumerConfiguration;
import io.nats.client.api.RetentionPolicy;
import io.nats.client.api.StreamConfiguration;
import io.nats.client.api.StreamInfo;
import io.nats.client.impl.NatsJetStreamMetaData;
import io.synadia.CommandLine;
import io.synadia.Workload;

import java.io.IOException;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;

import static io.nats.client.support.JsonUtils.printFormatted;

public class CustomWorkload extends Workload {
    public static final String DATA_STREAM_NAME = "cw-data";
    public static final String LOG_STREAM_NAME = "cw-log";
    public static final String DATA_SUBJECT_PREFIX = "d.";
    public static final String DATA_STREAM_SUBJECT = DATA_SUBJECT_PREFIX + ">";
    public static final String LOG_SUBJECT = "l";
    public static final String CONSUMER_PREFIX = "con-";
    public static final int CONSUMER_COUNT = 10000;
    public static final long PUBLISH_JITTER = 100;
    public static final int PUBLISH_THREAD_COUNT = 4;
    public static final int INFO_THREAD_COUNT = 8;
    public static final int PROGRESS_FREQUENCY = 100;
    public static final int INFO_REPORT_FREQUENCY = 500;

    public void init(CommandLine commandLine) {
        init("Custom Workload " + commandLine.action, commandLine);
        if (commandLine.args.isEmpty()) {
            throw new RuntimeException("Argument(s) Required. " + commands());
        }
    }

    private static String commands() {
        return "Commands: 'setup', 'list', 'clear', 'publish', 'info', 'local', 'results'";
    }

    @Override
    public void runWorkload() throws Exception {
        try (Connection nc = Nats.connect(getAdminOptions())) {
            String arg = commandLine.args.getFirst();
            switch (arg) {
                case "setup"   -> doSetup(nc);
                case "list"    -> doList(nc);
                case "clear"   -> doClear(nc);
                case "publish" -> doPublish();
                case "info"    -> doInfo();
                case "results" -> doResults(nc);
                default        -> System.out.println("Custom Workload unknown [" + arg + "] " + commands());
            }
        }
    }

    private void doSetup(Connection nc) throws IOException, JetStreamApiException {
        System.out.println("Custom Workload - Setup");
        System.out.println("Creating Streams...");
        JetStreamManagement jsm = nc.jetStreamManagement();
        safeDeleteStream(jsm, DATA_STREAM_NAME);
        StreamInfo si = jsm.addStream(StreamConfiguration.builder()
            .name(DATA_STREAM_NAME)
            .subjects(DATA_STREAM_SUBJECT)
            .retentionPolicy(RetentionPolicy.Limits)
            .maxMessages(1_000_000)
            .build());
        printFormatted(si.getJv());
        safeDeleteStream(jsm, LOG_STREAM_NAME);
        si = jsm.addStream(StreamConfiguration.builder()
            .name(LOG_STREAM_NAME)
            .subjects(LOG_SUBJECT)
            .retentionPolicy(RetentionPolicy.Limits)
            .maxAge(Duration.ofMinutes(5))
            .build());
        printFormatted(si.getJv());

        System.out.println("Creating Consumers...");
        long count = 0;
        for (int cx = 0; cx < CONSUMER_COUNT; cx++) {
            jsm.createConsumer(DATA_STREAM_NAME, ConsumerConfiguration.builder()
                .durable(toConsumerName(cx))
                .filterSubject(toSubjectName(cx))
                .build());
            progressInLoop(++count);
        }
        progressAfterLoop(count);
        List<String> list = jsm.getConsumerNames(DATA_STREAM_NAME);
        System.out.println(list.size());
    }

    private void doList(Connection nc) throws IOException, JetStreamApiException {
        System.out.println("Custom Workload - List Consumers");
        JetStreamManagement jsm = nc.jetStreamManagement();
        List<String> list = jsm.getConsumerNames(DATA_STREAM_NAME);
        list.forEach(System.out::println);
        System.out.println(list.size());
    }

    private void doClear(Connection nc) throws IOException, JetStreamApiException {
        System.out.println("Custom Workload - Clear Consumers");
        JetStreamManagement jsm = nc.jetStreamManagement();
        List<String> list = jsm.getConsumerNames(DATA_STREAM_NAME);
        int count = 0;
        for (String cn : list) {
            jsm.deleteConsumer(DATA_STREAM_NAME, cn);
            progressInLoop(++count);
        }
        progressAfterLoop(count);
    }

    private void doPublish() throws InterruptedException {
        System.out.println("Custom Workload - Publish");
        List<Options> options = roundRobinOptions(PUBLISH_THREAD_COUNT);
        List<Thread> threads = new ArrayList<>(PUBLISH_THREAD_COUNT);
        AtomicLong count = new AtomicLong();
        for (int x = 0; x < PUBLISH_THREAD_COUNT; x++) {
            Thread t = publishThread(x, count, options.get(x));
            t.start();
            threads.add(t);
        }
        for (Thread t : threads) {
            t.join();
        }
    }

    private static Thread publishThread(final Integer id, AtomicLong count, Options options) {
        return new Thread(() -> {
            try (Connection nc = Nats.connect(options)) {
                JetStream js = nc.jetStream();
                printInfoResult("Connect", id, -1, nc.getServerInfo().getServerId());
                int jsapi = 0;
                List<Integer> consumers = new ArrayList<>();
                for (int cx = 0; cx < CONSUMER_COUNT; cx++) {
                    consumers.add(cx);
                }
                while (true) {
                    Collections.shuffle(consumers);
                    for (Integer cx : consumers) {
                        jitter(PUBLISH_JITTER);
                        try {
                            js.publish(toSubjectName(cx), null);
                        }
                        catch (JetStreamApiException e) {
                            printInfoResult("Publish Exception:", id, ++jsapi, e);
                        }
                        progressInLoop(count.incrementAndGet());
                    }
                    progressAfterLoop(count.get());
                }
            }
            catch (IOException | InterruptedException e) {
                throw new RuntimeException(e);
            }
        });
    }

    private void doResults(Connection nc) throws IOException, JetStreamApiException {
        System.out.println("Custom Workload - Show Results");
        JetStreamSubscription sub = nc.jetStream().subscribe(LOG_SUBJECT);

        //noinspection InfiniteLoopStatement
        while (true) {
            try {
                Message m = sub.nextMessage(1000);
                if (m != null) {
                    System.out.println(new String(m.getData()) + " | " + stringify(m));
                }
            }
            catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
    }

    public static String stringify(Message msg) {
        NatsJetStreamMetaData meta = msg.metaData();
        return "StreamSeq: " + meta.streamSequence() + " | " + "ConSeq: " + meta.consumerSequence();
    }

    private void doInfo() throws InterruptedException {
        boolean background = commandLine.args.contains("background");
        System.out.println("Custom Workload - Info | background: " + background);
        List<Options> options = roundRobinOptions(INFO_THREAD_COUNT);
        List<Thread> threads = new ArrayList<>(INFO_THREAD_COUNT);
        List<List<String>> consumerNameLists = new ArrayList<>();
        for (int t = 0; t < INFO_THREAD_COUNT; t++) {
            List<String> list = new ArrayList<>();
            consumerNameLists.add(list);
        }
        int tx = INFO_THREAD_COUNT - 1;
        for (int cx = 0; cx < CONSUMER_COUNT; cx++) {
            if (++tx == INFO_THREAD_COUNT) {
                tx = 0;
            }
            List<String> list = consumerNameLists.get(tx);
            list.add(toConsumerName(cx));
        }

        for (int x = 0; x < INFO_THREAD_COUNT; x++) {
            Thread t = infoThread(x, background, consumerNameLists, options.get(x));
            t.start();
            threads.add(t);
        }

        for (Thread t : threads) {
            t.join();
        }
    }

    private static Thread infoThread(final Integer id, boolean background, List<List<String>> consumerNameLists, Options options) {
        return new Thread(() -> {
            long got = 0;
            long io = 0;
            long jsapi = 0;
            try (Connection nc = Nats.connect(options)) {
                JetStreamManagement jsm = nc.jetStreamManagement();
                JetStream js = nc.jetStream();
                infoResult(background, js, "Connect", id, -1, nc.getServerInfo().getServerId());
                List<String> list = consumerNameLists.get(id);
                while (true) {
                    for (String consumerName : list) {
                        try {
                            jsm.getConsumerInfo(DATA_STREAM_NAME, consumerName);
                            if (++got % INFO_REPORT_FREQUENCY == 0) {
                                infoResult(background, js, "Consumer Info", id, got, null);
                            }
                        }
                        catch (IOException e) {
                            infoResult(background, js, "INFO IO EX", id, ++io, e);
                        }
                        catch (JetStreamApiException e) {
                            infoResult(background, js, "INFO JSAPI EX", id, ++jsapi, e);
                        }
                    }
                }
            }
            catch (IOException | InterruptedException e) {
                throw new RuntimeException(e);
            }
        });
    }


    private static void infoResult(boolean background, JetStream js, String label, Integer id, long count, Object extra) {
        if (background) {
            submitInfoResult(js, label, id, count, null);
        }
        else {
            printInfoResult(label, id, count, null);
        }
    }

    private static void printInfoResult(String label, Integer id, long count, Object extra) {
        System.out.println(getInfoResultText(label, id, count, extra));
    }

    private static void submitInfoResult(JetStream js, String label, Integer id, long count, Object extra) {
        String text = getInfoResultText(label, id, count, extra);
        try {
            js.publish(LOG_SUBJECT, text.getBytes());
        }
        catch (IOException | JetStreamApiException ee) {
            System.err.println("[" + id + "] Result Publish Error | " + ee);
        }
    }

    private static String getInfoResultText(String label, Integer id, long count, Object extra) {
        return "Thread " + id
            + " | " + label
            + (count < 0 ? "" : " | " + count)
            + (extra == null ? "" : " | " + extra);
    }

    private static void progressAfterLoop(long count) {
        if (count % PROGRESS_FREQUENCY != 0) {
            System.out.println(count);
        }
    }

    private static void progressInLoop(long count) {
        System.out.print(".");
        if (count % PROGRESS_FREQUENCY == 0) {
            System.out.println(count);
        }
    }

    private static String toSubjectName(int cx) {
        return DATA_SUBJECT_PREFIX + cx;
    }

    private static String toConsumerName(int x) {
        return CONSUMER_PREFIX + x;
    }
}
