/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.synadia.CommandLine;

public class DebugWorkload extends AbstractCustomWorkload {

    @Override
    public void init(CommandLine commandLine) {
        init("Debug Workload", commandLine);
        initCustom(new String[0], new String[0]);
    }

    @Override
    protected boolean subRunWorkload(String arg) throws Exception {
        return true;
    }
}
