/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.synadia.CommandLine;

public class DebugWorkload extends AbstractCustomWorkload {

    @Override
    public void init(CommandLine commandLine) {
        customWorkloadInit("Debug Workload", true, commandLine);
    }

    @Override
    protected String[] commands() {
        return new String[] {};
    }

    @Override
    protected boolean subRunWorkload(String arg) throws Exception {
        return true;
    }
}
