/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.nats.client.*;
import io.nats.client.api.PublishAck;
import io.nats.client.api.StreamConfiguration;
import io.nats.client.support.JsonValueUtils;
import io.synadia.CommandLine;
import io.synadia.utils.Debug;

import java.io.IOException;
import java.util.concurrent.ThreadLocalRandom;

public class FailgroundSim extends AbstractCustomWorkload {
    private String dataStreamName;
    private String dataSubject;
    private long dataMaxMessages;

    private String publishJob;
    private long publishReportFrequency;
    private long publishJitter;
    private int publishMinMessageSize;
    private int publishMaxMessageSize;

    @Override
    public void init(CommandLine commandLine) {
        init("Failground Sim", commandLine);

        dataStreamName = JsonValueUtils.readString(params.jv, "data_stream_name", "data");

        initCustom(
            new String[]{"pub"},
            new String[]{dataStreamName}
        );

        dataSubject = JsonValueUtils.readString(params.jv, "data_subject", "d");
        dataMaxMessages = JsonValueUtils.readLong(params.jv, "data_max_messages", 1_000_000);
        Debug.info(workLabel, "dataStreamName", dataStreamName);
        Debug.info(workLabel, "dataSubject", dataSubject);
        Debug.info(workLabel, "dataMaxMessages", dataMaxMessages);

        publishJob = JsonValueUtils.readString(params.jv, "publish_job", "Publish");
        publishReportFrequency = JsonValueUtils.readLong(params.jv, "publish_report_frequency", 100);
        publishJitter = JsonValueUtils.readLong(params.jv, "publish_jitter", 100);
        publishMinMessageSize = JsonValueUtils.readInteger(params.jv, "publish_min_message_size", 100);
        publishMaxMessageSize = JsonValueUtils.readInteger(params.jv, "publish_max_message_size", 1000);
        Debug.info(workLabel, "publishJob", publishJob);
        Debug.info(workLabel, "publishReportFrequency", publishReportFrequency);
        Debug.info(workLabel, "publishJitter", publishJitter);
        Debug.info(workLabel, "publishMinMessageSize", publishMinMessageSize);
        Debug.info(workLabel, "publishMaxMessageSize", publishMaxMessageSize);
    }

    @Override
    protected boolean subRunWorkload(String arg) throws Exception {
        switch (arg) {
            case "pub"   -> doWorker(publishJob, 1, this::pubWorker);
            default      -> { return false; }
        }
        return true;
    }

    private byte[] getData(String pubId) {
        byte[] idData = (pubId + " ").getBytes();
        int len = ThreadLocalRandom.current().nextInt(publishMinMessageSize, publishMaxMessageSize) + idData.length;
        byte[] data = new byte[len];
        ThreadLocalRandom.current().nextBytes(data);
        System.arraycopy(idData, 0, data, 0, idData.length);
        return data;
    }

    @SuppressWarnings("InfiniteLoopStatement")
    private Runnable pubWorker(Options options, int tix, WorkState ws) {
        return () -> {
            try (Connection nc = Nats.connect(options)) {
                JetStream js = nc.jetStream();
                printConnect(nc, publishJob, ws.workId, NO_TIX);
                jitter(publishJitter / 10);
                long lastSeq = -1;
                while (true) {
                    try {
                        if (publishJitter > 0) {
                            //noinspection BusyWait
                            Thread.sleep(ThreadLocalRandom.current().nextLong(publishJitter));
                        }

                        String pubId = NUID.nextGlobal();
                        PublishOptions po = lastSeq == -1
                            ? PublishOptions.builder().build()
                            : PublishOptions.builder().expectedLastSequence(lastSeq).build();
                        PublishAck pa = js.publish(dataSubject, getData(pubId), po);
                        lastSeq = pa.getSeqno();

                        long count = ws.increment();
                        if (count % publishReportFrequency == 0) {
                            log(js, publishJob, ws.workId, NO_TIX, count, ws.elapse(), true);
                        }
                    }
                    catch (IOException | JetStreamApiException e) {
                        log(js, publishJob, ws.workId, ws.elapse(), e);
                    }
                    jitter(publishJitter);
                }
            }
            catch (InterruptedException | IOException e) {
                throw new RuntimeException(e);
            }
        };
    }

    @Override
    protected void subDoSetup(Connection nc, JetStreamManagement jsm) throws IOException, JetStreamApiException, InterruptedException {
        addStream(jsm, StreamConfiguration.builder()
            .name(dataStreamName)
            .subjects(dataSubject)
            .maxMessages(dataMaxMessages)
            .build());
    }
}
