/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.nats.jsmulti.JsMulti;
import io.nats.jsmulti.settings.Arguments;
import io.nats.jsmulti.settings.Context;
import io.synadia.CommandLine;

public class Publisher extends Workload {

    public Publisher(CommandLine commandLine) {
        super(commandLine);
    }

    @Override
    public void subRunWorkload() throws Exception {
        Arguments a = Arguments.instance()
            .addJsonConfig(params.jvMultiConfig.toJson());
        Context ctx = new Context(a);
        a.printCommandLine();
        JsMulti.run(ctx);
    }
}
