/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.nats.client.Connection;
import io.nats.client.KeyValueManagement;
import io.nats.client.Nats;
import io.synadia.CommandLine;
import io.synadia.Workload;

import static io.synadia.utils.Constants.SETUP;

public class Setup extends Workload {
    private final Which which;

    public Setup(CommandLine commandLine) {
        super("Setup " + commandLine.action, commandLine);
        this.which = Which.instance(SETUP, commandLine.action);
    }

    @Override
    public void runWorkload() throws Exception {
        try (Connection nc = Nats.connect(getAdminOptions())) {
            switch (which) {
                case Tracking -> doTracking(nc);
                case Save     -> doTracking(nc);
                case Testing  -> doTesting(nc);
            }
        }
    }

    private void doTesting(Connection nc) throws Exception {
        createStream(params.streamConfig, nc.jetStreamManagement());
    }

    private void doTracking(Connection nc) throws Exception {
        KeyValueManagement kvm = nc.keyValueManagement();
        createBucket(params.multiBucket, kvm);
        createBucket(params.statsBucket, kvm);
        createBucket(params.profileBucket, kvm);
        createStream(params.streamConfig, nc.jetStreamManagement());
    }
}
