/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.nats.client.Connection;
import io.nats.client.Nats;
import io.synadia.CommandLine;
import io.synadia.Workload;

public class SetupTesting extends Workload {
    public SetupTesting(CommandLine commandLine) {
        super("Setup Testing", commandLine);
    }

    @Override
    public void runWorkload() throws Exception {
        try (Connection nc = Nats.connect(getAdminOptions())) {
            createStream(params.streamConfig, nc.jetStreamManagement());
        }
    }
}
