/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.nats.client.Connection;
import io.nats.client.KeyValueManagement;
import io.nats.client.Nats;
import io.nats.client.Options;
import io.nats.client.api.KeyValueConfiguration;
import io.synadia.CommandLine;
import io.synadia.Workload;
import io.synadia.tools.Debug;

import java.util.List;

public class SetupTracking extends Workload {
    public SetupTracking(CommandLine commandLine) {
        super("Setup Tracking", commandLine);
    }

    @Override
    public void runWorkload() throws Exception {
        Options options = getAdminOptions("Setup Tracking");
        try (Connection nc = Nats.connect(options)) {
            KeyValueManagement kvm = nc.keyValueManagement();
            List<String> names = kvm.getBucketNames();
            if (names.contains(params.trackingBucket)) {
                Debug.info(workloadName, "Bucket already exists.");
            }
            else {
                KeyValueConfiguration kvc = KeyValueConfiguration.builder()
                    .name(params.trackingBucket)
                    .maxHistoryPerKey(1)
                    .build();
                Debug.info(workloadName, kvm.create(kvc));
            }
        }
        catch (Exception e) {
            e.printStackTrace();
            System.exit(-1);
        }
    }
}
