/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia.workloads;

import io.nats.client.Connection;
import io.nats.client.KeyValueManagement;
import io.nats.client.Nats;
import io.synadia.CommandLine;
import io.synadia.Workload;

public class SetupTracking extends Workload {
    public SetupTracking(String defaultLabel, CommandLine commandLine) {
        super(defaultLabel, commandLine);
    }

    @Override
    public void runWorkload() throws Exception {
        try (Connection nc = Nats.connect(getAdminOptions())) {
            KeyValueManagement kvm = nc.keyValueManagement();
            createBucket(params.statsBucket, kvm);
            createBucket(params.profileBucket, kvm);
            createStream(params.streamConfig, nc.jetStreamManagement());
        }
    }
}
