/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class RunnerTest {
    @Test void someLibraryMethodReturnsTrue() {
        Runner classUnderTest = new Runner();
        assertTrue(true, "someLibraryMethod should return 'true'");
    }
}
