/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.synadia;

import org.junit.jupiter.api.Test;

class RunnerTest {
    @Test void someLibraryMethodReturnsTrue() {
        Runner classUnderTest = new Runner();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
